### 사전 준비 사항 

#### (1) uv add (터미널)

```bash
uv add rank_bm25
```

#### (2) .env 파일 세팅
```bash
OPENAI_API_KEY = ""
HF_TOKEN = ""
```

#### (3) pdf 파일 세팅
pdf 파일 100개를 `data/raw/files` 에 위치합니다.  
eval 파일(csv 2개, jsonl 1개)을 `data/raw/eval` 에 위치합니다.(*30개 파일 합친 버전)

#### 실행 방법

1. 처음 1회(커널 새로 시작): 처음부터 끝까지 순서대로 실행
2. exp1 결과 저장 확인
3. <실험 ID 변경> 셀의 exp_id 를 변경 후 새로운 실험 진행 (실험 결과 저장 확인 후 커널 재시작)  
\*커널 재시작하지 않는 경우, 실험 ID 변경 + 실험 진행 섹션 코드만 실행해도 됨.(OOM 발생 가능성이 있어 권장하지 않음.)
4. 원하는 실험로 변경 및 반복

In [1]:
import preprocess.pp_v4 as pp4
import preprocess.pp_v5 as pp5
import preprocess.pp_v6 as pp6
from preprocess.pp_basic import docs

# pp4.show_sample(docs, "all")
pp5.show_sample(docs, "all")

/Users/won/dev/00_codeit/0_mission/200_DL_RAG/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

문서: (사)벤처기업협회_2024년 벤처확인종합관리시스템 기능 고도화 용역사업 .pdf
총 청크 수: 77

=== 청크 0 (377자) ===
## 2024 2024 2024 2024 2024 2024 년 년 년 년 년 년 ｢ ｢ ｢ ｢ ｢ ｢ 벤처확인종합관리시스템 벤처확인종합관리시스템 벤처확인종합관리시스템 벤처확인종합관리시스템 벤처확인종합관리시스템 벤처확인종합관리시스템 기능 기능 기능 기능 기능 기능 고도화 고도화 고도화 고도화 고도화 고도화｣ ｣ ｣ ｣ ｣ ｣ 2024 년 ｢벤처확인종합관리시스템 기능 고도화｣ 용역사업 (p.1)
-( 복수의결권주식 , 스톡옵션 , 성과조건부주식 ) -

## 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 (p.1)
2024. 03.

## 목 차 (p.2)

## Ⅰ . 추진개요 (p.3)

=== 청크 1 (1315자) ===
## 1 추진배경 및 방향 (p.3)
□ 「 벤처기업육성에 관한 특별조치법 」 ( 이하 ' 벤처기업법 ') 복수의결권주식 , 스톡옵 션 ( 주식매수선택권 ), 성과조건부주식교부계약 (RS) 등의 기능 고도화 및 이관 , 신규 구축업무를 本 과업에서 추진
( 복수의결권주식 ) 벤처기업법 제 16 조의 11 에 따라 발행된 복수의결권주 식 보고 업무처리 시스템 구축
복수의결권이란 ? 모든 주주는 1 주당 하나의 의결권을 갖는 주주평등원칙 ( 상법 ) 과 별도로 비상장 벤처기업 창업자에게만 1 주당 최대 10 배의 의결권 행사를 부여하는 제도
⚬ ( 스톡옵션 * ) 벤처기업법 제 16 조의 3 에 따라 부여된 벤처기업 부여 , 취소 · 철회 신고 및 업무시스템 구축
스톡옵션
스톡옵션이란 ? 비상장 벤처기업 임 · 직원 및 기업 성장에 기여한 자에게 미리 정한 가격 ( 행 사가격 ) 으로 신주를 인수하거나 자기의 주식을 매수할 수 있는 권리 혹은 주식의 시가와 행 사가격의 차액을 청구할 수 있는 권리를 부여하는 제도
-중소벤처 24 內 스톡옵션 신청 기능 이관을 추진하며 , 과거 데이터 정 제 및 적재 등을 통한 데이터 이관 추진
⚬ ( 성과조건부주식 * ) 벤처기업법 제 16 조의 19 에 따라 성과조건부주식교부 계약의 신고 및 업무처리 시스템 구축
성과조건부주식이란 ? 비상장 벤처기업 임ㆍ직원 및 특정인에게 자기주식 부여를 약속하되 , 일정 재직기간 및 조건을 충족해야 주식이 부여 대상자에게 귀속되도록 제한을 둔 주식
□ 복수의결권주식 발행 보고 및 스톡옵션 신고기능은 기존 시스템 내 벤 처확인 이력정보와 신고자 ( 벤처기업 ) 의 정보와 연동
( 사 업 명 ) 2024 년 「 벤처확인종합관리시스템 기능 고도화 」 용역사업 -복수의결권주식 , 스톡옵션 , 성과조건부주식교부 기능 구축 및 고도화
□ ( 사업기간 ) 계약일로부터 150 일
1 차 오픈 : 2024.07.10.
성과조건부 및 스톡옵션 오픈
** 2 차 오픈 : 2024.09
월 中 GrandOpen
□ ( 소요예산 ) 352,000,000 원 ( 부가가치세 포함 )
□ ( 계약방식 ) 제한경쟁입찰 ( 협상에 의한 계약 ) 에 의한 선정 *
( 근거 ) 「국가를 당사자로 하는 계약에 관한 법률」 시행령 제 21 조 , 제 43 조
□ (선정 방법) 본 사업은 전문기술이 요구되는 사업으로 기술력이 높은 업체 를 선정하고 협상을 통해 요구사항을 반영할 수 있는 '협상에 의한 계약' 방식 으로 추진
(선정 절차) 제안서 평가는 기술평가 (90%) 와 가격평가 (10%) 를 합산하여 종합평가점수로 산출 ( 배정한도 85% 이상 , 고득점순으로 협상적격자 결 정 )

=== 청크 2 (692자) ===
## 행정기관 및 공공기관 정보시스템 구축․운영 지침 (p.4)

## 제18조(평가배점) (p.4)
행정기관 등의 장은 기술력이 우수한 사업자를 선정하여 정보화사업의 품질을 확보하기 위해 국가계약법 시행령 제 43 조의 2, 지방계약법 시행령 제 44 조에 따라서 협상에 의한 계약체결 방법 을 우선적으로 적용하고 , 기술능력평가 배점한도를 90 점으로 한다 .
□ (대기업 참여 제한) 「소프트웨어 진흥법」제 48 조제 2 항에 따라 , 사업금액 20 억원 미만 계약은 대기업 참여 제한

## Ⅱ . 사업 추진방안 (p.5)

## 1 추진목표 (p.5)
◈ 벤처확인 연계를 통한 복수의결권 및 스톡옵션 시스템 고도화

## 추진 목표 (p.5)
◈ 복수의결권주식, 스톡옵션 업무시스템 구축
◈ 스톡옵션 데이터 이관 작업 수행
◈ 신청접수 및 처리 결과 알림 One-Stop Service

## 2 추진체계 및 역할 (p.6)

## □ 추진체계 (p.6)

## □ 추진역할 (p.6)

## 중소벤처기업부 (p.6)

## 벤처기업확인기관 (p.6)
( 시스템 고도화 발주 )

## 자문위원 (p.6)
( 법률 , 검수 · 검사 등 )

## 사업 수행업체 (p.6)
벤처확인종합관리시스템 기능 고도화 수행 ( 복수의결권 , 스톡옵션 , 성과조건부주식 )

## 운영 유지관리 업체 (p.6)
現 시스템 유지관리업무 수행 中

=== 청크 3 (567자) ===
## 3 추진방안 (p.7)
□ ( 구축 인터뷰 ) 복수의결권주식 및 스톡옵션 시스템 구축을 위한 사전 기능 요구사항에 대한 충 분 한 인터 뷰 * 진행 , 분석 ㆍ기 획 보고서 제출
시스템 Risk-Point 해결 / 개선을 위한 중소벤처기업부 , 중소벤처기업부 지방청 (13 개 ) 미 팅
□ ( 데이터분석 ) 스톡옵션 데이터 분석 을 통한 통계 자 료 및 타 기관 연계정 보 현황 수요조사 진행
벤처확인종합관리시스템 벤처확인유 형 별 입수된 정보를 이용한 스톡옵 션 부여신고 간소화 서비스 추진ㆍ 분석 , 회원연계 ( 중소벤처 24) 분석
스톡옵션 데이터 및 문서 정제 / 적재 작업 수행
스톡옵션 , 복수의결권주식 확인 및 행정업무 수행을 위한 별도 백 오 피 스를 구성 , 외 부 * 접속을 위한 접근제어 솔루션 탑 재 여부 분석
공동인 증 서 로 그 인을 통해 접속 中 , 개선방안 제시 및 로 그 인 기록 보관
벤처확인종합관리시스템 內 탑재를 위한 시스템 분석 * 자료 ( 영향도 분석 ) 제출
데이터 연계 , 기정원 인프라 구성 (TA 분석 ), 상용 SW 활 용 및 Risk( 라이선스 등 ) 분석

=== 청크 4 (289자) ===
## 4 추진일정 (p.8)

## □ 추진일정 ( 안 ) (p.8)
★ 복수의결권 1 차 오픈일 ('24.07.10) 준수 , 스톡옵션 GrandOpen( 미정 )
주요내용
1차 오픈
중간보고 및 완 료 보고 ( 중소벤처기업부 , 벤처기업확인기관 )
-사용자 매 뉴얼 작성 , 업무용 매 뉴얼 을 통한 교육 2 회
주 단위 시스템 진행 보고 ( 벤처기업확인기관 )
시스템 안정화를 위한 1 개월 이상 안정화 운영인력 상주

## Ⅲ . 사업 추진내용 (p.9)

## 1 복수의결권 / 스톡옵션 개 념 도 (p.9)

=== 청크 5 (644자) ===
## □ 메뉴 구성 ( 안 ) (p.9)
※ 성과조건부주식교부 신고기능은 스톡옵션 기능 메뉴 규성과 유사함
-복수의결권 및 스톡옵션 업무시스템 메뉴 구성 * 및 디 자인 시안 제출
업무시스템 효율 성을 고 려 한 최적의 메뉴 구성 ( 안 ) 제안 , 메뉴 구성 ( 안 ) 의 명칭 은 변경 보 완 될 수 있 음
□ ( 대민사이트 ) 벤처확인종합관리시스템 內 복수의결권주식 , 스톡옵션 메 뉴 로 구성
-복수의결권주식 발행보고 양 식 출력
-스톡옵션 부여 신고자 , 스톡옵션 부여 대상자 정보 확인 페 이지 구축 ( 스 톡옵션 신고 양 식 출력 )
-스톡옵션 부여신고 지방청 (13 개 ) 자동 배정 , 스톡옵션 부여신고 ( 취소 ㆍ철회 포함 )
□ ( 백오피스 ) 복수의결권주식 발행보고 및 스톡옵션 신고 업무처리를 위한 각 별도의 업무시스템 구축
중소벤처기업부 및 13 개 지방중소벤처기업청 접속 , 성과조건부주식교 부계약 업무처리 시스템도 동일하게 구축
벤처확인 이력정보 연동 및 요건 충족 여부 등의 이상 관제 모 니 터 링 기능 구 현
벤처확인 재발 급 , 벤처확인 취소
공시대상기업 집 단 계 열 회사 편 입 , 기업상장 여부 등
-스톡옵션 부여신고 자동배정 프로 세 스 구 현 , 스톡옵션 부여자 알림 기능 , 업무 담 당자별 차등 권한 등

=== 청크 6 (672자) ===
## 2 업무 및 시스템 현황 (p.11)
□ ( 복수의결권주식 ) 「 벤처기업육성에 관한 특별조치법 」 시행에 따 른 복수 의결권주식 발행 보고 기능 오픈 中
복수의결권주식 발행 보고 ( 보완 ) 기능 고도화
비상장 벤처기업 요건 확인 후 복수의결권주식 발행 , 사 후 관리 ( 상장 , 대 기업 집 단 편 입 등 ) 모 니 터 링 구 현
비상장 벤처기업 요건 확인 후 스톡옵션 부여신고 , 새 로운 기 획 을 통한 스톡옵션 신청 , 운영관리 구축
스톡옵션 신고 확인 관리자 (BackOffice) * 페 이지 별도 구성 中 , 공동인 증 서 로 그 인
중소벤처기업부 , 13 개 지방중소기업청 담 당 공무원 로 그
-스톡옵션 배정 및 처리 현황 통계 기능 구축 , 부여대상자 ( 부 분 ) 취소 기능개선 등
□ ( 인프라 ) 중소기업기술정보진흥원 클 라우 드 (Paas-TA) 환 경에 설 치 운영되 고 있으며 , 벤처확인종합관리시스템 內 시스템 탑 재에 따 른 상용 SW 적 용 가능
복수의결권주식 , 스톡옵션 별도 관리자 시스템 구축을 위한 PaaS-TA 자원 할당 ( 운영 / 개발 ) 제안

## < 벤처확인종합관리시스템 인프라운영 현황 > (p.12)
※ 중소벤처 24 제공 서비스 : SSO 이지 패 스 , 레 포 팅툴 , DB 암호 화 솔루션

## 3 복수의결권 추진내용 (p.13)

=== 청크 7 (394자) ===
## □ 복수의결권주식 제도 요약 (p.13)
□ ( 비상장 벤처기업 ) 복수의결권주식 발행보고 前 비상장 벤처기업 여부 확인 , 요건 충족 기업만 가능
( 비상장 ) 복수의결권주식 발행보고 기업 법인등록 번호 조회
-대기업기업 집 단 계 열 회사 편 입 여부 ( 데이터포 털 연계 )
( 벤처확인 ) 복수의결권주식 발행보고 기업 사업자등록 번호 , 법인등록 번 호 , 벤처확인발 급번호 조회
-( 벤처확인 프로세스 ) 벤처확인 재확인  , 또 는 취소  ( 청문절차 ), 재발 급  등 복수의결권주식 발행 신고 가능 여부 체 크
-주주 총 회 결의 시 벤처확인이 유 효 하다 면 신청 가능
□ ( 복수의결권주식 기능개선 ) 복수의결권주식 발행보고 출력 기능개선 , 기 업 My 페 이지 활 동 이력

=== 청크 8 (1041자) ===
## < My페이지 기업 활동이력 예시 > (p.15)
① 벤처확인 이력 기준 복수의결권주식 발행보고 , 스톡옵션 신고 이력이 있는 경우 노 출
-벤처확인 유 효 시작일 ~ 만 료 일 기간 내 정관개정을 통한 복수의결권주식 발행보고 , 스톡옵션 신고 가 능
-이상 : 대기업 집 단계 열편 입 , 상장 , 폐 업 / 휴 업 등이 있는 경우 표시
② 벤처확인이력 기준 복수의결권주식 발행보고는 '23.11.17 부터 가능 , 스톡옵션은 98 년부터 신고 가능
-사용자 활 동이력은 업무시스템에 동일하게 노 출되도록 구 현
③ 벤처확인발 급번호 , 복수의결권주식 접수 번호 , 스톡옵션 접수 번호 기준 출력 기능개발
( 정관변경 ) 특별결의를 통한 변경 정관 업로 드 기능 구 현
※ 엄 격한 주주동의 , 발행주식 총 수의 4 분 의 3 이상 동의로 가결
특수관계인으로부터 받 은 투 자를 제 외 한 투 자금액이 누 적 100 억원 & 마 지 막 50 억원 이상
벤처확인 정보 연동을 통한 사용자 정보 입력 간소화
제출서류 업로 드 기능 구 현 ( 제출서류 이력 관리 기능 포함 )
< 복수의결권주식 ( 발행 , 변경 ) 필 수 기재 항목 >
※ 복수의결권주식 ( 발행 , 주요사항 변경 ) 보고서 양 식 제공 , 보고서 양 식 분석 을 통 환 시스템 화 면 기 획 필 요
< 사 후 변경에 따 른 복수의결권주식의 보통주 전 환 >
□ ( 복수의결권주식 발행보고 ) 복수의결권주식 받 은 자의 성 명 , 발행일자 , 발행 수 량 을 벤처확인종합관리시스템 공시
복수의결권주식 발행보고 서 문서 출력 기능 구 현
「 벤처기업육성에 관한 특별조치법 시행규칙 」 별지 제 9 호 참 고
복수의결권주식 변경보고 서 문서 출력 기능 구 현
-변경 신고 완 료 후 복수의결권 발행 변경 전 / 후 비교 정보 출력
복수의결권주식 변경사항 공시 기능 구 현
□ ( 복수의결권 위 반 ( 허위 거짓 ) 발행 신고기능 ) 복수의결권주식 발행 위반행 위 신고기능 구 현
개인정보 수 집 및 이용 동의 절차 기능 구 현 , 신고자 통신사 인 증
-위반행위 신고작성 방법 안내 페 이지 구

=== 청크 9 (604자) ===
## 4 스톡옵션 추진내용 (p.19)
□ ( 데이터 이관 ) 중소벤처 24 內 벤처기업 스톡옵션 ( 주식매수선택권 ) 신고를 위해 가입된 회원정보 * 및 과거 각 종 데이터 / 문서 이관
벤처확인종합관리시스템 內 탑 재를 위한 회원 중복가입 등 데이터 검 증 ( 회원통합 )
신고접수 및 보완요청 , 최종수리 단계별 신고자 알림
스톡옵션 신고 물량 배정 기능 구축 ( 중소벤처기업부 지방청 )
벤처기업법 제 16 조의 3 비상장 벤처기업 확인
-주주 총 회 결의 시 벤처확인이 유 효 하다 면 신청 가능 , 과거 벤처확인이
력이 있는 경우 해당 유 효 기간 내 주주종회 결의시 신청 가능
☞ ( 기능 구축 ) 대민사이트 스톡옵션 신고 前 증 권시장 ( 유가 증 권시장 , 코 스 탁 시장 , 코넥 스시장 ) 에 상장되지 않 은 비상장 벤처기업 여부 확인
< 비상장 벤처기업 여부 조회(안) >

## 1안) 비상장 / 벤처기업 동시 조회 (p.20)
2안) 벤처기업 조회 / 비상장 별도 확인
연도별 행사가격 분 포
-배정 조건 外 부득이 재배정 이 슈 가 발행할 수 있 음 , 부여신고 접수 번호 를 통한 재배정 이력 조회 기능 구축 ( 지방청 배정 이력 전체 조회 가 능 )

=== 청크 10 (1145자) ===
## □ 스톡옵션 부여신고 (p.21)
비상장 벤처기업 조회 후 스톡옵션 부여 신고서 작성 기능 구 현
( 출력 ) 「 벤처기업육성에 관한 특별조치법 시행규칙 」 별지 제 3~4 호 참 고
※ ( 중요 ) 기재된 화 면 은 참 고자 료 이며 , 별도 화 면 기 획 및 제안 진행
NOE5
기업정보 , 업무 담 당자 입력 간소화 방안 기 획
기업 명 , 대표자 명 등 일반적인 입력정보
사업자등록 번호 , 벤처확인발 급번호 등을 통한 주식 매수선택권 부여 신고 가능 조회기능 탑 재 3. 벤처확인정보 연계
벤처확인발 급번호 , 벤처확인일 , 유 효 시간
※ 벤처확인이력조회가 되지 않 는 경우 문의 case1. 벤처확인만 료 case2. 사업자등록 번호 와 벤처확인정보 불 일치 case3. 벤처확인만 료 일 기준 벤처재확인 프로 세 스 진행 中
부여주식종류 별도 코드 로 관리
액 면 가 단위 ( 원 ), 숫 자한 글 정보 표기
부여인원 주식수 , 행사가격 총 합과 동일해야 함
olue
50(22492482(8102)
0184 522
OPA84 2191
92 4 849
1. 1841219391 842(2 48165 913 4818 12)|
2.78084 28898 325 1( 4 16593 4 18 22)|
3. (992 087712(3 (4816593 4818 39)
정관에 ' 스톡옵션 ( 주식매수선택권 ) 주식의 행사기간 ' 이 규정되어 있는지 여부 中 행사기간은 주식매수 선택권 부여 결의사항 행사기간과 연동되어 체 크 되 어야 함
주주 총 회특별결의 , 이사회 결의에 따 른 입력창 , 페 이지부터 임시 저 장 기능 활 성화
(+) 연 번 추가를 통한 부여인원 등록 , 부여인원 대 량 등록기능 개발
부여인원의 핸드폰번호 등록 ( 개인정보보 호 에 관한 신고자 대리 등록에 따 른 등록 동의 )
핸드폰번호 를 통해 부여된 인원의 부여주식 정보 안내
자격 , 부여방법 코드값 으로 관리 ,
부여인원 주식 총 합 자동 계산
항목별 첨 부 파 일 업로 드 복수
4 91091 71909 942( 48163593 4818 42)
49 49
40 9 28
438s
R3E 049
4400-248409-8948
VOZAN
243500 B73E
WOST
MOFNO
080389948 483
RADOLA 2891 9940R 49(EMES
NHEE

=== 청크 11 (676자) ===
## □ 스톡옵션 취 소 ( 부분 )/ 철 회 신고 (p.22)
스톡옵션 부여 신고 건에 대한 주식매수선택권 피 부여자 ( 부 분 ) 취소 , 철회 기능
( 부 분 ) 취소 , 철회 신고 통보 결과 기능 구 현
-피 부여자 취소 및 철회 신고 사항 알림 기능 구 현

## □ 스톡옵션 부여대상자 (p.23)
부여대상자는 시스템 로 그 인 후 My 페 이지를 통해 스톡옵션 부여 현황 및 행사 정보 확인

## < My페이지 스톡옵션 부여대상자 예시 > (p.23)

## Ⅳ . 제안요청 내용 (p.24)

## 1 과업수행방법 (p.24)

## □ 과업 착 수 (p.24)
본 시스템 기능 고도화 용역사업은 과업 시작일로부터 10 일 이내 착 수하 여야 함
계약상대자는 계약체결일로부터 10 일 이내 다 음 과 같 은 서류를 벤처확 인기관에 문서로 제출해야 함
∨ 착 수계
∨ 책 임기술자 선임계
∨ 책 임기술자 이력서 및 기술자격 증 사본
∨ 참 여기술자 이력서 및 기술자격 증 사본
∨ 보안 각 서 및 보안대 책
∨ 과업수행계 획 서
∨ 기타 필 요사항

## □ 과업수행계 획 서 제출 (p.24)
( 과업수행계 획 서 ) 계약서 , 과업내용서 등의 내용을 근거로 작성
( 계 획승 인 ) 계약상대자는 과업수행계 획 서를 벤처기업확인기관의 승 인을 득 한 후 이에 따라 과업 수행
제 출서류 목 록

=== 청크 12 (606자) ===
## 2 제안요청 일반사항 (p.25)
□ 제안 업체는 시스템 기능 고도화 완 료 후 기능 확장성 등을 고 려 하여 제안하여야 함
□ 제안 업체는 제안하는 모든 부 분 에 포 괄 적인 책 임을 가지며 , 제안 시점 에서 사업수행요건 미충족 업체는 선정 대상에서 제 외 함
□ 제안규격의 만족 여부는 벤처기업확인기관에서 제시하는 평가 기준 등 에 의해 심 사함
□ 전산시스템 운용 및 유지관리에 대처할 수 있는 구체적 기술이전 , 교육 계 획 및 지원계 획 을 제시해야 함
□ 특별한 사유가 없 는 한 본 시스템 기능 고도화사업은 사업 기간 中 개 발 완 료 및 테 스트 가능하여야 하며 , 하자 보 증 기간 내 하자보수 및 유 지관리 계약이행에 대한 모든 책 임을 져 야 함
□ 안정적이고 확장 가능한 최적의 시스템 개발하며 개발업무의 각 종 서식 및 코드 , 시스템 간 통합 및 연계 , 전산 망 간 연계 등 정보화 표준을 준용하여 개발해야 함
□ 시스템 개발과정에서 취득한 일체 모든 정보는 외 부로 유출 또 는 발 설 해서는 안 되며 , 만약 사업 과정에서 보안사고 발 생 시 업체에서는 일 체 민 형 사상의 책 임을 지고 , 벤처기업확인기관이 입은 손 해에 대하여 배상해야 함

=== 청크 13 (721자) ===
## 3 제안요청 필 수사항 (p.26)
□ ① 보안성을 고 려 한 시스템 구성 및 운영방안 , ② 보안성 강 화 및 관리의 용이성을 위한 추가지원 가능 사항 ( 필 요시 ) 을 제시해야 함
□ 시스템 장 애 발 생 시 , 즉각 복구할 수 있는 체제를 구축해야 함
□ 향 후 시스템 확장성을 위해 시스템 기능 고도화 관련 표준을 최대한 준수
□ 제안서에 기재되지 않 은 사항이라 할지라도 제품성능에 필 요한 사항은 벤처기업확인기관과 협의를 통해 공 급 ( 납 품 ) 하여야 함
□ 최종 인수 결과 시스템 운영 불 가로 ' 계약조건 미충족 ' 으로 판 단 시 , 벤 처기업확인기관의 요구에 의해 구축한 모든 시스템을 철거 · 회수하여야 하며 , 그 비용은 제안업체에서 일체 부 담 하고 이로 인한 벤처기업확인 기관의 손 해를 배상해야 함
□ 본 과업의 시스템은 유기적으로 데이터 교 환 이 가능하여야 하며 , 타 기관 의 시스템 연계가 가능해야 함
□ 시스템 기능 고도화 과정에서 취득한 정보에 대한 보안 관리 방법 등에 대한 제시 및 시스템 구축 후 하자보수를 위한 방안을 제시해야 함

## □ 요구사항 정의표 (p.27)
※ 사업 내용이 변경 될 경우 과업변경절차에 따라 상 호 협의하여 결정하며 , 제안서 작성 시 제안요청서 요구사 항에 명 시되지 않았 으나 제안 업체 판 단으로 추가되어야 할 요구사항에 대해서는 별도 표시하여 추가 작성 가능함

## □ 요구사항 상세 (p.28)

=== 청크 14 (158자) ===
## 가 기능 요구사항(Sy s te m Fu nction R e qu ire m ent) (p.28)
요구사항
요구사항
요구사항
요구사항
상세설명
세부내용
SFR-016
요구사항
복수의결권주식
복수의결권
신고정보
복수의결권
요구사항정의서
변경보고
(SFR-015)
(SFR-015)

=== 청크 15 (638자) ===
## 나 성능 요구사항( P erfor m ance R e qu ire m ent) (p.43)

## 다 시스템 장비 구성 요구사항(( Equ ip m ent C o m po s ition R e qu ire m ent) (p.45)

## 라 인터페이스 요구사항(Sy s te m I nterface R e qu ire m ent) (p.47)

## 바 테 스트 요구사항( T e s t R e qu ire m ent) (p.53)

## 사 보안 요구사항(Sec u rity R e qu ire m ent) (p.55)

## 자 제약사항( C on s train s R e qu ire m ent) (p.61)

## 세부내용 (p.62)

## [ 표준화 공통 ] (p.62)
❍ 위에서 제시한 방안 등을 준용하여 시스템 구축 시 고 려 되어야 할 표준화 방 안 및 요구사항에 대한 구체적인 준수방안을 제시하고 적용해야 함
❍ 전자정부 구축을 위한 기술 아키텍 처 표준을 제시한 ' 행정기관 및 공공기관 정보시스템 구축 · 운영지침 ( 행정안전부 고시 )' 를 준수
❍ 본 사업에서 구축 될 전자정부표준프 레 임 워크 를 기반으로 시스템을 개발해야 하며 , 성능 및 안정성에 문제가 발 생 할 경우 주관기관과 협의하여 결정해야 함

=== 청크 16 (192자) ===
## [ 정보화 업무 표준 ] (p.62)
❍ 주관기관에서 제시하는 각 종 표준 ( 프로 세 스 , 정보 , 사업관리 등 ) 을 준수해야 함
❍ 표준운영 체계 , 절차 및 보안체계 , 정 책 등 각 종 서식에 대하여 기존 표준체 계에 따 르 거나 표준이 없 으 면 표준 형 식을 정의하고 주관기관의 승 인을 득한 후 형 식에 맞 게 작성해야 함

=== 청크 17 (755자) ===
## [ 정보화 기반 표준 ] (p.62)
❍ 행정기관 및 공공기관 정보시스템 구축 · 운영지침 ( 행정안전부 고시 )' 의 기술적 용 계 획 에 따라 본 사업에 해당하는 기술표준을 준수하여야 함

## [ 행정정보 데이터 베 이스 표준화 ] (p.62)

## [ 전자정부 웹 호환 성 준수 ] (p.62)
❍ 전자정부서비스의 호환 성 확보를 위해 ' 전자정부서비스 호환 성 준수지침 ( 행 정안전부 고시 )' 을 준수해야 함
❍ 웹 사이트 구축 표준은 ' 전자정부 웹 표준 준수지침 ( 행정안전부 고시 )' 을 준수 해야 함
❍ 웹 표준을 적용하여 IE(10, 11, 그 이상 ), Firefox, Safari, Opera, Chrome 등 3 개 이상의 브 라우 저 에서 웹 사이트가 정상 동작하도록 범 용성 및 호환 성이 확보되도록 적용해야 함
❍ 웹 사이트에 비표준기술 (Acitve X, EXE, Java Applet 등 ) 이 포함되지 않 도록 개발하여야 함

## [ 웹 접근성 표준 준수 ] (p.62)
❍ 다 음 지침에 따 른 장 애 인 접근성을 준수하여 적용해야 함
-인터 넷 웹 콘텐츠 접근성 지침
-웹 접근성 향상을 위한 국가표준기술 가이 드 라인
❍ ' 한국 형 웹 컨텐츠 접근성 지침 (KCS.OT-10.0003/R3)' 적용
❍ 웹 접근성 평가도구 (KADAO-WAH) 로 점검시 항목별 95% 이상 준수
❍ 웹 접근성 세 부 준수 요건의 경우 주관기관과 협의하여 조정할 수 있 음
산 출 정보
요구사항
요구사항
요구사항

=== 청크 18 (49자) ===
## 요구사항 상세설명 (p.63)
세부내용
요구사항
요구사항
요구사항
요구사항
상세설명

=== 청크 19 (790자) ===
## [ 개발보안 및 개인정보 보 호 표준 준수 ] (p.63)
❍ ' 전자정부 SW 개발 · 운영자를 위한 소프트웨어 개발보안 가이 드 ( 행정안전부 )' 를 준수해야 함
❍ ' 표준 개인정보 보 호 지침 ( 행정안전부 예 규 )' 을 준수해야 함
❍ ' 공공기관 홈 페 이지 개인정보 노 출방지 가이 드 라인 ( 행정안전부 )' 을 준수해야 함
❍ 국가정보원 , 중소벤처기업부 등의 정보보안 요건을 충족해야 함
사업수행계
COR-004
제약사항
❍ 다 양 한 디바 이스 (PC, 스 마 트 폰 , 태블 릿 PC 등 ) 와 브 라우 저 지원을 위한 스 마 트 기 반의 반 응형 웹 기술 적용
❍ OSMU(One Sourece Multi Use) 의 개 념 에 따라 하나의 소스로 다 양 한 사이 즈 의 화 면 에 최적화된 UI 가 구성 될 수 있도록 구 현
❍ 모 바 일 전자정부 관련 웹 접근성 및 웹 호환 성을 준수하여 구조 설 계
❍ 모 바 일 서비스에 적합하고 이용 빈 도가 높은 정보위주의 메뉴 설 계
❍ 모 바 일 기기를 통해 홈 페 이지 접속 시 모 바 일 홈 페 이지로 자동전 환 될 수 있 도록 구성
사업수행계
COR-005
제약사항
중소벤처
기술지원
중소벤처
기술지원이
기술확약서
벤처확인시스템과
기술확약서를
세부내용

## 차 프로 젝 트 관리 요구사항( P ro j ect M gm t R e qu ire m ent) (p.65)

## 카 프로 젝 트 지원 요구사항( P ro j ect S u pport R e qu ire m ent) (p.68)

## □ 산출 물 목록 (p.73)

=== 청크 20 (16자) ===
## □ 특수사항 (p.74)

=== 청크 21 (477자) ===
## ◦ 윈 백 (Winback) (p.74)
-제안요청서에 증설 또 는 변경으로 표기한 경우에는 기존 제품과의 호환 성을 고 려 하여야 하며 , 필 요 시 기존 제품 수 량까 지 포함하여 다 른 제품
으로 윈 백 제안을 할 수 있 음
-윈 백 ( 기존 제품과 다 른 제품으로 제안한 경우 포함 ) 시 각 종 프로 그램 수정 등에 필 요한 기술지원 및 기존 제품 수 량 의 교체는 제안업체가 부 담 하 여야 함
-그 밖 에 윈 백 ( 기존 제품과 다 른 제품으로 제안한 경우 포함 ) 시 필 요하거나 그 로 인해 발 생 되는 일체의 사항은 사업자가 모 두 책 임지고 해결하여 야 함
-제안업체는 사업수행계 획 서 제출 시 윈 백 완 료 가능한 일정을 명 시하 여야 하며 , 추 후 사업수행과정에서 해당 일시 까 지 윈 백 을 완 료 하기 어 렵 다고 판 단되는 경우 발주처와 협의하여야 함
소프트웨어 개발보안 ( 시 큐 어 코 딩 ) 관련 가이 드 준수

=== 청크 22 (503자) ===
## ◦ 정보보 호 제품 준수사항 (p.75)
-( 정보보 호 제품 운영 ) 정보보 호 제품은 CC 인 증 ( 네 트 워크 기반 제품 및 컴퓨 팅 기반 제품은 EAL2 이상 ) 을 획 득한 제품이어야 하며 , 암호 모 듈 검 증 대 상제품은 검 증필 암호 모 듈 탑 재제품이어야 함
※ 국가 공공기관 정보보 호 제품 도입기준 및 절차 ( 국가정보원 ) 준수
-( 제품변경 시 재인 증 ) 제안업체는 취약점 또 는 기능적 결함 등이 발 견 되어 정보보 호 제품의 SW 패 치 또 는 HW 사 양 을 변경하는 경우 , 납 품한 동 제품의 취약점 및 결함을 즉 시 보완하고 , 변경 후 수일 이내에 변경된 사 양 으로 재인 증 추진 등 관련 사항을 조치하여야 함
※ 기존 보안적합성 검 증필 제품도 국가 ‧ 공공기관 구축 후 국가 전문기관의 현 장 실 사 위 주의 사 후 검 증 필 요
-정보보 호 제품 관련 처리기준은 국가정보원 기준 및 중소벤처기업부 , 벤처기업확인기관 관련 지침에 의거 준용하여야 함

=== 청크 23 (261자) ===
## ◦ 개인정보보 호 법 (p.75)
※ 공공기관의 개인정보 취 급 시 준수해야 하는 공통법규 ( 법률 , 지침 , 매 뉴얼 고시 등 ) 및 평가대 상 사업의 특성에 따라 적용되는 관련 법 등을 참 고하여 평가기준을 수 립 해야 함
-서비스 보안성 강 화를 위해 운영서 버 의 개인정보 유출 탐 지 등 모 니 터 링 , 개발서 버 시 험 운영을 위한 개인정보 관련 모의 데이터 추출 ‧생 성 등의 방안을 마 련하여야 함

## ◦ 구축시스템의 모의시 험 (p.76)

=== 청크 24 (546자) ===
## ◦ 기타조건 (p.76)
-본 사업의 추진과 관련하여 제안요청서에 명 시되지 않 은 사항에 대해 서는 최근 고지된 관련 규정 및 고시를 준용함
-수요기관 위임발주 및 S/W 분 리발주 사업의 경우 본 사업 이 외 사업 에 대한 사유로 인해 사업기간이 중단 등 조정 될 수 있 음
-본 사업은 20 억원미만 사업으로「대기업인 소프트웨어 사업자가 참 여 할 수 있는 사업금액의 하한 ( 과 학 기술정보통신부 고시 ) 」고시를 준수하며 , 대기업 및 중 견 기업은 입찰에 참 여할 수 없음
-본 사업은「소프트웨어 진흥법」제 48 조 제 4 항 , 「독점규제 및 공정거 래 에 관한 법률」제 31 조에 따라 ' 상 호 출자제한기업 집 단소속회사 ' 는 입찰에 참 여할 수 없음
-「국가를 당사자로 하는 계약에 관한 법률 시행령」제 43 조에 따라 본 사업 은 사업자 선정 시 ' 협상에 의한 계약체결방식 ' 우선 적용
-본 사업은 「소프트웨어 진흥법」제 50 조에 따라 계약당사자가 과업내용 변경으로 인한 계약내용 변경이 필 요한 경우 과업 심 의위원회 개최 요 청할 수 있 음

=== 청크 25 (364자) ===
## Ⅴ . 입찰 관련 사항 (p.78)

## 1 입찰 및 낙 찰방식 (p.78)
□ ( 입찰방식 ) 제한경쟁입찰
중소기업자간 경 쟁 * 및 대기업 참 여 사업금액 하한기준 (20 억 ) 대상 ** 사업
** ( 근거 ) 「대기업인 소프트웨어사업자가 참 여할 수 있는 사업금액의 하한」 ( 과기부 고시 )
□ ( 낙 찰자 선정방식) 협상에 의한 계약
( 근거 ) 「국가를 당사자로 하는 계약에 관한 법률」 시행령 제 43 조 및 제 43 조의 2
( 제안서 평가기준 ) 기술평가 90%, 가격평가 10% 적용
( 근거 ) 「협상에 의한 계약체결기준」 ( 기 획 재정부 계약 예 규 )
※ 입찰진행 관련 세 부사항은 벤처기업확인기관 입찰공고문에 따 름

=== 청크 26 (1246자) ===
## 2 입찰 참 가자격 (p.78)
□ 「 국가를 당사자로 하는 계약에 관한 법률 」 시행령 제 12 조에 의한 입찰 참가자격을 갖추고 , 동법 시행령 제 76 조에 의해 부정 당 업체로 입찰 참가 제한을 받 고 있 지 않은 업체
□ 중소기업제품 구매 촉 진 및 판 로지원에 관한 법률 제 9 조에 의거 직접 생 산 증명 서 ( 정보시스템개발서비스 , 세 부품 명코드 : 8111159901) 를 소지한 자
□ 「 중소기업제품 구매 촉 진 및 판 로지원에 관한 법률 」 제 9 조 따 른 직접 생 산 확인 증명 서 ( 정보시스템 개발서비스 ) 를 소지한 업체
□ 본 사업은 추정 금액 20 억 원 미 만 인 사업 으로 써 「 소프트 웨 어 진 흥 법 」 제 48 조의 규정에 따라 대기업 및 「 독점규제 및 공정거 래 에 관한 법률 」 제 14 조에 따라 지정된 상 호출 자제한기업 집단 에 속하는 기업은 참여할 수 없음
※ 대기업인 소프트웨어사업자의 참 여 가능 사업금액의 하한
※ 중소기업이 대기업이 된지 5 년 이내의 기업 , 상 호 출자제한기업 집 단에 속하지 않 는 중 견 기업 ( 증빙 서류 : 한국소프트웨어산업협회 소프트웨어 신고확인서 )
※ 상 호 출자제한기업 집 단 소속기업은 사업금액에 관계 없 이 원칙적으로 공공 SW 사업에 참 여제한 ( 소프트웨어진흥법 제 48 조 제 3 항 )
□ 공동수 급 업체는 모 두 상기의 입찰 참 가자격을 구비하여야 함
공동수 급 업체 구성원은 「 국가를 당사자로 하는 계약에 관한 법률 」 시행령 제 12 조 ( 경 쟁 입찰의 참 가자격 ) 및 동법 시행규칙 제 14 조 ( 입찰 참 가자격 요건의 증명 ) 규정에 저 촉 되지 않아 야 함
당사자 간 책 임 , 권리 , 의무관계를 명백히 규정한 ' 공동수 급 표준협정서 ' 를 제출하여야 함
공동수 급 체 구성원은 5 개 이하로 구성하며 , 구성원별 계약 참 여 최소 지 분율 은 10% 이상이어야 함
공동수 급 의 경우 ' 공동계약 운용요령 ( 기 획 재정부 계약 예 규 제 651 호 , '23.06.16.)' 규정을 적용하며 , 동일업체가 복수의 공동수 급 에 참 여할 수 없음
□ 하도 급 을 포함한 경우 다 음 사항을 준수해야 함
하도 급 사전 승 인
-본 사업의 하도 급 의 경우 「 소프트웨어 진흥법 」 제 51 조 하도 급 계약 전
에 발주기관으로부터 사전 승 인을 받아 야 함
하도 급 비 율 제한
다만 , 동법 제 51 조 제 3 항 각 호 에 해당하는 경우에는 해당하지 않음
재 하도 급은 허용하지 않음

=== 청크 27 (661자) ===
## 3 입찰시 유의사항 (p.81)
□ 제안내용에 대한 확인을 위하여 추가자 료 요청 또 는 현 지 실 사를 할 수 있으며 , 입찰 참 가자는 이에 응 하여야 함
□ 낙 찰자로 결정된 이 후 에 컨 소시 엄 구성원을 변경할 수 없음
□ 제안서 인력은 컨 소시 엄 구성원의 자사 인력으로 구성하여야 함
채 용 예 정 인력인 경우에는 별도로 이를 명 기하고 , 계약체결 전 까 지 채 용 을 완 료 하여야 함
적법한 파견 근로자는 자사 인력으로 간주하나 , 원소속사를 반 드 시 명 기 하여야 함
컨 소시 엄 소속 외 의 인력을 하도 급 으로 간주하며 , 주관기관의 승 인을 얻 지 못 할 경우에는 컨 소시 엄 구성원의 자사 인력으로 대체하여야 함
※ 단 , 상용 S/W, 패키 지 등의 서비스 지원인력 , 외 부 자문인력 등 통상적인 개발인력이 아 닌 경우는 제안서에 명 기하지 말 것 ( 참 여인력에서 제 외 )
□ 계약상의 사업을 수행함에 있어 부 실 , 조 잡 또 는 부당하게 하거나 , 부정 한 행위를 한 사업자는 향 후 참 여 제한을 받 을 수 있 음
□ 본 사업의 수행에 필 요한 모든 비용은 가격입찰금액에 포함시 켜 야 함
□ 사업추진 결과 발 생 한 지식재산권은 수요기관과 공동소유 함

## Ⅵ . 제안서 작성요령 (p.82)

## 1 제안서 작성방법 (p.82)

=== 청크 28 (276자) ===
## □ 제안 서 의 효력 (p.82)
제 출 된 제안 서 내용 은 주관사에서 요청하지 않 는 한 수정 ‧ 추가 ‧ 대체할 수 없으며 기재 내용은 실제 와 일치 해 야 함
주관사에서 필 요 시 입찰 참 가자에 대하여 추가 제안이 나 추가자료를 요 청할 수 있으며 , 제출된 자 료 는 제안서와 동일한 효 력을 가 짐
제안서의 모든 기재사항은 객 관적으로 입 증 할 수 있는 관계 서류를 첨 부 하여 사 실 을 기재하여야 하며 , 허 위 작성한 사 실 이 판명될 경우에는 평 가대상에서 제 외 함

=== 청크 29 (968자) ===
## □ 제안 서 작성지 침 ( 권장사항 ) (p.82)
제출된 제안 서 는 일절 반 환하지 않으며 , 본 제안과 관련된 일체의 소요 비용 은 입찰참가자 부 담 으로 함
제안자는 제시된 ' 제안 서 작성 서 식 ' 을 준용하여 작성 하여야 함
제안서의 모든 내용은 참고자료 및 근거 자료가 제시 되어야 하며 , 주요 제안내용 에 대하여는 공인된 증빙 자료를 첨 부 해야 함
제안서는 제안요청 서 에 기술된 요구사항을 충 분 히 만족 할 수 있 는 방안이 포함 되어야 하며 , 제안요청 내용에 기술된 부문별 요구사항 에 대해서는 보 다 구체 적 이고 상세한 방안을 기 술 해야 함
제안서의 내용은 명확한 용어를 사용하여 표현 해야 하며 , 계량화가 가능한 것은 계량화 하여 표기
본 제안요청서에 명기되지 아 니 한 사항이라도 본 사업 수행 상 반 드 시 필 요하 다 고 판단 되는 경우에는 사업내용에 반 영 돼 야 하며 , 입찰 금액 에 포 함 한 것 으로 간주
제안업체는 제안서의 내용이 허위 또는 이행 불 가능한 내용 으로 작성 된 사실 이 발 견될 경우 일체의 책임 을 져 야 함
계약 후 에도 제안서가 본 제안요청의 요구조건과 상이하 게 작성되 었다
고 판 명 될 경우 는 계약자 부 담으 로 사업내용에 포함 해야 함
제출되는 서류가 사본 인 경우 ' 사실과 상위 없음 ' 음 명기 하여 법인 또 는 조 달 청 사용인 감으 로 날 인 하여 제출해야 함
제안서에 누락 된 내용 이나 추진방향 변경 시 향후 사업의 추진에 반드 시 필 요 하다고 인지 될 경우에는 사업 발주기관의 요청 으 로 수정할 수 있음
제출된 서류는 일체 반 환하지 않으며 , 사업결과에 따 른 시스템 및 산 출 물 의 소유권 은 계약 당 사자 간 공동 으 로 소유함
□ ( 개발 SW 의 공동 활용 ) 본 사업을 통해 개발되는 소프트웨어는 용역계 약일반조건 제 56 조 ( 계약목적 물 의 지식재산권 귀속 등 ) 에 따라 타 기관과 공 동 활 용하지 않음

=== 청크 30 (761자) ===
## 2 제안서 평가방법 (p.85)

## □ 기 술 평가 (p.85)
총 점 100 점 기준으로 각 평가항목에 대한 점수를 합산하여 평가
「 소프트 웨 어기 술 성평가기준 」 제20219 8 호 (과 학 기 술 정보통신부 고시)를 기준
기술평가항목 및 배점기준은 ' 기술성 평가 기준표 ' 에 의함

## 가격평가 (p.85)
「 협상에 의한 계약체결 기준 」 제 656호 (기 재 부 계약예 규 )에 따름

## 종합평가 (p.85)
종합평가점수 산출
-종합 평가점수 = 기술 평가점수 + 입찰가격
평가점수
평가비 율 : 기 술 평가( 9 0 % ), 가격평가(10 % )
평가점수 결과는 소수점 다 섯째 자리에서 반 올 림

## □ 협상 적 격자 선정 및 협상 순서 (p.85)
협상순서는 협상적격자의 기술능력평가점수와 입찰가격평가 점수를 합산하 여 합산점수의 고득점 순에 따라 결정
-협상이 성 립 된 때 에는 다 른 협상적격자와의 협상은 실 시하지
-모든 협상적격자와 협상 결 렬 시 재공고 입찰에 부 칠 수 있

## □ 동점시 처리방 침 (p.86)
종합평가점수가 동점인 경우 기술평가 점수가 높은 업체
기술평가점수도 동일한 경우 기술능력의 세 부평가항목 중 배점이 큰 평 가항목에서 점수가 높은 업체

## ◦ 정성평가 (100 점 ) (p.87)

## [ 기 술 성 평가 기준표 ] (p.87)

## Ⅰ . 제안개요 (p.91)

## Ⅱ . 일 반 현황 (p.91)
제안업체 일반 현황
제안업체의 조직 및 인원
수행조직 및 업무 분 장

=== 청크 31 (65자) ===
## Ⅲ . 전 략 및 방법 론 (p.91)
사업 이해도
추진전 략
적용기술
표준 프 레 임 워크 적용
개발 방법 론

=== 청크 32 (643자) ===
## Ⅳ . 기 술 및 기능 (p.91)
시스템 장비구성 요구사항
기능 요구사항
보안 요구사항
데이터 요구사항
시스템 운영 요구사항
제약사향

## Ⅴ . 성능 및 품질 (p.91)
성능 요구사항
품질 요구사항
인터 페 이스 요구사항
테 스트 요구사항

## Ⅵ . 프로 젝 트 관리 (p.91)
관리방법 론
관리역 량
일정계 획
개발장비

## Ⅶ . 프로 젝 트지원 (p.91)
품질보 증
시 험 운영
교육 훈 련
유지보수
기 밀 보안
비상대 책

## Ⅷ . 기 타 사항 (p.91)

## 4 제안서 세 부 작성지침 (p.92)

## Ⅶ . 별지서식 및 붙임 (p.94)

## □ 별지 서 식 (p.94)
< 별지서식 1 호 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 제안서 표지
< 별지서식 2 호 > 제안요청서 수용 여부 참 조표
< 별지서식 3 호 > 일반 현황 및 연 혁
< 별지서식 4 호 > 자본금 및 매출액 현황
< 별지서식 5 호 > 사업수행 조직도
< 별지서식 6 호 > 기술적용계 획 표
< 별지서식 7 호 > 소프트웨어사업 하도 급 계 획 서
< 별지서식 7-1 호 > 하도 급 적정성 판 단 자기평가표
< 별지서식 8 호 > 공동수 급 표준협정서 ( 공동이행방식 )
< 별지서식 9 호 > 합의 각 서

=== 청크 33 (156자) ===

In [2]:
pp6.show_sample(docs, "all")

문서: (사)벤처기업협회_2024년 벤처확인종합관리시스템 기능 고도화 용역사업 .pdf
총 청크 수: 193
표 포함 청크 수: 129
표 청크 인덱스: [3, 5, 11, 13, 14, 17, 19, 20, 24, 28] ...

=== 청크 0 (377자) ===
[meta] section_path=2024 2024 2024 2024 2024 2024 년 년 년 년 년 년 ｢ ｢ ｢ ｢ ｢ ｢ 벤처확인종합관리시스템 벤처확인종합관리시스템 벤처확인종합관리시스템 벤처확인종합관리시스템 벤처확인종합관리시스템 벤처확인종합관리시스템 기능 기능 기능 기능 기능 기능 고도화 고도화 고도화 고도화 고도화 고도화｣ ｣ ｣ ｣ ｣ ｣ 2024 년 ｢벤처확인종합관리시스템 기능 고도화｣ 용역사업 | page=1 | label=section_header | table_id=
## 2024 2024 2024 2024 2024 2024 년 년 년 년 년 년 ｢ ｢ ｢ ｢ ｢ ｢ 벤처확인종합관리시스템 벤처확인종합관리시스템 벤처확인종합관리시스템 벤처확인종합관리시스템 벤처확인종합관리시스템 벤처확인종합관리시스템 기능 기능 기능 기능 기능 기능 고도화 고도화 고도화 고도화 고도화 고도화｣ ｣ ｣ ｣ ｣ ｣ 2024 년 ｢벤처확인종합관리시스템 기능 고도화｣ 용역사업 (p.1)
-( 복수의결권주식 , 스톡옵션 , 성과조건부주식 ) -

## 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 제안요청서 (p.1)
2024. 03.

## 목 차 (p.2)

## Ⅰ . 추진개요 (p.3)

=== 청크 1 (1315자) ===
[meta] section_path=Ⅰ . 추진개요 > 1 추진배경 및 방향 | page=3 | label=section_header | table_id=
## 1 추진배경 및 방향 (p.3)
□ 「 벤처기업육성에 관한 특별조치법 」 ( 이하 ' 벤처기업법 ') 복수의결권주식 , 스톡옵 션 ( 주식매수선택권 ), 성과조건부주식교부계약 (RS) 등의 기능 고도화 및 이관 , 신규 구축업무를 本 과업에서 추진
( 복수의결권주식 ) 벤처기업법 제 16 조의 11 에 따라 발행된 복수의결권주 식 보고 업무처리 시스템 구축
복수의결권이란 ? 모든 주주는 1 주당 하나의 의결권을 갖는 주주평등원칙 ( 상법 ) 과 별도로 비상장 벤처기업 창업자에게만 1 주당 최대 10 배의 의결권 행사를 부여하는 제도
⚬ ( 스톡옵션 * ) 벤처기업법 제 16 조의 3 에 따라 부여된 벤처기업 부여 , 취소 · 철회 신고 및 업무시스템 구축
스톡옵션
스톡옵션이란 ? 비상장 벤처기업 임 · 직원 및 기업 성장에 기여한 자에게 미리 정한 가격 ( 행 사가격 ) 으로 신주를 인수하거나 자기의 주식을 매수할 수 있는 권리 혹은 주식의 시가와 행 사가격의 차액을 청구할 수 있는 권리를 부여하는 제도
-중소벤처 24 內 스톡옵션 신청 기능 이관을 추진하며 , 과거 데이터 정 제 및 적재 등을 통한 데이터 이관 추진
⚬ ( 성과조건부주식 * ) 벤처기업법 제 16 조의 19 에 따라 성과조건부주식교부 계약의 신고 및 업무처리 시스템 구축
성과조건부주식이란 ? 비상장 벤처기업 임ㆍ직원 및 특정인에게 자기주식 부여를 약속하되 , 일정 재직기간 및 조건을 충족해야 주식이 부여 대상자에게 귀속되도록 제한을 둔 주식
□ 복수의결권주식 발행 보고 및 스톡옵션 신고기능은 기존 시스템 내 벤 처확인 이력정보와 신고자 ( 벤처기업 ) 의 정보와 연동
( 사 업 명 ) 2024 년 「 벤처확인종합관리시스템 기능 고도화 」 용역사업 -복수의결권주식 , 스톡옵션 , 성과조건부주식교부 기능 구축 및 고도화
□ ( 사업기간 ) 계약일로부터 150 일
1 차 오픈 : 2024.07.10.
성과조건부 및 스톡옵션 오픈
** 2 차 오픈 : 2024.09
월 中 GrandOpen
□ ( 소요예산 ) 352,000,000 원 ( 부가가치세 포함 )
□ ( 계약방식 ) 제한경쟁입찰 ( 협상에 의한 계약 ) 에 의한 선정 *
( 근거 ) 「국가를 당사자로 하는 계약에 관한 법률」 시행령 제 21 조 , 제 43 조
□ (선정 방법) 본 사업은 전문기술이 요구되는 사업으로 기술력이 높은 업체 를 선정하고 협상을 통해 요구사항을 반영할 수 있는 '협상에 의한 계약' 방식 으로 추진
(선정 절차) 제안서 평가는 기술평가 (90%) 와 가격평가 (10%) 를 합산하여 종합평가점수로 산출 ( 배정한도 85% 이상 , 고득점순으로 협상적격자 결 정 )

=== 청크 2 (444자) ===
[meta] section_path=Ⅰ . 추진개요 > 1 추진배경 및 방향 > 행정기관 및 공공기관 정보시스템 구축․운영 지침 | page=4 | label=section_header | table_id=
## 행정기관 및 공공기관 정보시스템 구축․운영 지침 (p.4)

## 제18조(평가배점) (p.4)
행정기관 등의 장은 기술력이 우수한 사업자를 선정하여 정보화사업의 품질을 확보하기 위해 국가계약법 시행령 제 43 조의 2, 지방계약법 시행령 제 44 조에 따라서 협상에 의한 계약체결 방법 을 우선적으로 적용하고 , 기술능력평가 배점한도를 90 점으로 한다 .
□ (대기업 참여 제한) 「소프트웨어 진흥법」제 48 조제 2 항에 따라 , 사업금액 20 억원 미만 계약은 대기업 참여 제한

## Ⅱ . 사업 추진방안 (p.5)

## 1 추진목표 (p.5)
◈ 벤처확인 연계를 통한 복수의결권 및 스톡옵션 시스템 고도화

## 추진 목표 (p.5)
◈ 복수의결권주식, 스톡옵션 업무시스템 구축
◈ 스톡옵션 데이터 이관 작업 수행
◈ 신청접수 및 처리 결과 알림 One-Stop Service

=== 청크 3 (93자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=5 | label=table | table_id=1
[표] p.5 table_1
추진과제 | 세부 실행내용
추가사항 | ⑦ 타 기관 API 연계를 통한 정보 확인 ⑧ 입력정보 & 서류제출 간소화 , 정보보안 솔루션 적용

=== 청크 4 (246자) ===
[meta] section_path=추진 목표 > 2 추진체계 및 역할 | page=6 | label=section_header | table_id=
## 2 추진체계 및 역할 (p.6)

## □ 추진체계 (p.6)

## □ 추진역할 (p.6)

## 중소벤처기업부 (p.6)

## 벤처기업확인기관 (p.6)
( 시스템 고도화 발주 )

## 자문위원 (p.6)
( 법률 , 검수 · 검사 등 )

## 사업 수행업체 (p.6)
벤처확인종합관리시스템 기능 고도화 수행 ( 복수의결권 , 스톡옵션 , 성과조건부주식 )

## 운영 유지관리 업체 (p.6)
現 시스템 유지관리업무 수행 中

=== 청크 5 (188자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=6 | label=table | table_id=2
[표] p.6 table_2
구 분 | 역 할
중소벤처기업부 | ㆍ사업 총괄 운영ㆍ관리 감독
벤처기업확인기관 | ㆍ벤처확인제도 운영기관 ㆍ사업계 획 수 립 , 제안요청서 작성 ㆍ사업관리 및 검사 ㆍ사업수행 및 운영업무
자문위원 | ㆍ시스템 구축 및 법률 자문 등
운영 유지관리 업체 | ㆍ벤처확인종합관리시스템 운영 유지관리 업무 수행 中

=== 청크 6 (584자) ===
[meta] section_path=추진 목표 > 3 추진방안 | page=7 | label=section_header | table_id=
## 3 추진방안 (p.7)
□ ( 구축 인터뷰 ) 복수의결권주식 및 스톡옵션 시스템 구축을 위한 사전 기능 요구사항에 대한 충 분 한 인터 뷰 * 진행 , 분석 ㆍ기 획 보고서 제출
시스템 Risk-Point 해결 / 개선을 위한 중소벤처기업부 , 중소벤처기업부 지방청 (13 개 ) 미 팅
□ ( 데이터분석 ) 스톡옵션 데이터 분석 을 통한 통계 자 료 및 타 기관 연계정 보 현황 수요조사 진행
벤처확인종합관리시스템 벤처확인유 형 별 입수된 정보를 이용한 스톡옵 션 부여신고 간소화 서비스 추진ㆍ 분석 , 회원연계 ( 중소벤처 24) 분석
스톡옵션 데이터 및 문서 정제 / 적재 작업 수행
스톡옵션 , 복수의결권주식 확인 및 행정업무 수행을 위한 별도 백 오 피 스를 구성 , 외 부 * 접속을 위한 접근제어 솔루션 탑 재 여부 분석
공동인 증 서 로 그 인을 통해 접속 中 , 개선방안 제시 및 로 그 인 기록 보관
벤처확인종합관리시스템 內 탑재를 위한 시스템 분석 * 자료 ( 영향도 분석 ) 제출
데이터 연계 , 기정원 인프라 구성 (TA 분석 ), 상용 SW 활 용 및 Risk( 라이선스 등 ) 분석

## 4 추진일정 (p.8)

=== 청크 7 (219자) ===
[meta] section_path=추진 목표 > 4 추진일정 > □ 추진일정 ( 안 ) | page=8 | label=section_header | table_id=
## □ 추진일정 ( 안 ) (p.8)
★ 복수의결권 1 차 오픈일 ('24.07.10) 준수 , 스톡옵션 GrandOpen( 미정 )
주요내용
1차 오픈
중간보고 및 완 료 보고 ( 중소벤처기업부 , 벤처기업확인기관 )
-사용자 매 뉴얼 작성 , 업무용 매 뉴얼 을 통한 교육 2 회
주 단위 시스템 진행 보고 ( 벤처기업확인기관 )
시스템 안정화를 위한 1 개월 이상 안정화 운영인력 상주

=== 청크 8 (697자) ===
[meta] section_path=Ⅲ . 사업 추진내용 | page=9 | label=section_header | table_id=
## Ⅲ . 사업 추진내용 (p.9)

## 1 복수의결권 / 스톡옵션 개 념 도 (p.9)

## □ 메뉴 구성 ( 안 ) (p.9)
※ 성과조건부주식교부 신고기능은 스톡옵션 기능 메뉴 규성과 유사함
-복수의결권 및 스톡옵션 업무시스템 메뉴 구성 * 및 디 자인 시안 제출
업무시스템 효율 성을 고 려 한 최적의 메뉴 구성 ( 안 ) 제안 , 메뉴 구성 ( 안 ) 의 명칭 은 변경 보 완 될 수 있 음
□ ( 대민사이트 ) 벤처확인종합관리시스템 內 복수의결권주식 , 스톡옵션 메 뉴 로 구성
-복수의결권주식 발행보고 양 식 출력
-스톡옵션 부여 신고자 , 스톡옵션 부여 대상자 정보 확인 페 이지 구축 ( 스 톡옵션 신고 양 식 출력 )
-스톡옵션 부여신고 지방청 (13 개 ) 자동 배정 , 스톡옵션 부여신고 ( 취소 ㆍ철회 포함 )
□ ( 백오피스 ) 복수의결권주식 발행보고 및 스톡옵션 신고 업무처리를 위한 각 별도의 업무시스템 구축
중소벤처기업부 및 13 개 지방중소벤처기업청 접속 , 성과조건부주식교 부계약 업무처리 시스템도 동일하게 구축
벤처확인 이력정보 연동 및 요건 충족 여부 등의 이상 관제 모 니 터 링 기능 구 현
벤처확인 재발 급 , 벤처확인 취소
공시대상기업 집 단 계 열 회사 편 입 , 기업상장 여부 등
-스톡옵션 부여신고 자동배정 프로 세 스 구 현 , 스톡옵션 부여자 알림 기능 , 업무 담 당자별 차등 권한 등

=== 청크 9 (559자) ===
[meta] section_path=Ⅲ . 사업 추진내용 > 2 업무 및 시스템 현황 | page=11 | label=section_header | table_id=
## 2 업무 및 시스템 현황 (p.11)
□ ( 복수의결권주식 ) 「 벤처기업육성에 관한 특별조치법 」 시행에 따 른 복수 의결권주식 발행 보고 기능 오픈 中
복수의결권주식 발행 보고 ( 보완 ) 기능 고도화
비상장 벤처기업 요건 확인 후 복수의결권주식 발행 , 사 후 관리 ( 상장 , 대 기업 집 단 편 입 등 ) 모 니 터 링 구 현
비상장 벤처기업 요건 확인 후 스톡옵션 부여신고 , 새 로운 기 획 을 통한 스톡옵션 신청 , 운영관리 구축
스톡옵션 신고 확인 관리자 (BackOffice) * 페 이지 별도 구성 中 , 공동인 증 서 로 그 인
중소벤처기업부 , 13 개 지방중소기업청 담 당 공무원 로 그
-스톡옵션 배정 및 처리 현황 통계 기능 구축 , 부여대상자 ( 부 분 ) 취소 기능개선 등
□ ( 인프라 ) 중소기업기술정보진흥원 클 라우 드 (Paas-TA) 환 경에 설 치 운영되 고 있으며 , 벤처확인종합관리시스템 內 시스템 탑 재에 따 른 상용 SW 적 용 가능
복수의결권주식 , 스톡옵션 별도 관리자 시스템 구축을 위한 PaaS-TA 자원 할당 ( 운영 / 개발 ) 제안

=== 청크 10 (87자) ===
[meta] section_path=Ⅲ . 사업 추진내용 > 2 업무 및 시스템 현황 > < 벤처확인종합관리시스템 인프라운영 현황 > | page=12 | label=section_header | table_id=
## < 벤처확인종합관리시스템 인프라운영 현황 > (p.12)
※ 중소벤처 24 제공 서비스 : SSO 이지 패 스 , 레 포 팅툴 , DB 암호 화 솔루션

=== 청크 11 (447자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=12 | label=table | table_id=6
[표] p.12 table_6
차트 툴 | 1 식 | SB Chart v2
PDF 뷰 어 | 1 식 | ePapyrus StreamDocs v1.0
PDF 변 환 | 1 식 | ePapyrus PDF Gateway v8.0
PKI 공인인 증 | 1 식 | MagicLine v4.0
키 보 드 보안 | 1 식 | TouchEn nxKey v1.0-Explorer, TouchEn nxKey v1.0_Multi-Browser
업로 드 | 1 식 | RAON K Upload 2018
검 색엔 진 | 1 식 | Konan Search 5
그 리 드 툴 | 1 식 | SBGrid v2.0
위변조방지 | 1 식 | e-Page SAFER V2.5 Basic Package
화 면캡쳐 방지 | 1 식 | e-Page SAFER Web DRM Pack for Cross OS V2.5 Basic package

=== 청크 12 (49자) ===
[meta] section_path=Ⅲ . 사업 추진내용 > 3 복수의결권 추진내용 | page=13 | label=section_header | table_id=
## 3 복수의결권 추진내용 (p.13)

## □ 복수의결권주식 제도 요약 (p.13)

=== 청크 13 (228자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=13 | label=table | table_id=7
[표] p.13 table_7
항 목 | 내 용
① 발행자격 및 보유자격 | ① 발행자격 및 보유자격
발행자격 | 비상장 주식회사인 벤처기업 에 한정
② 발행요건 | ② 발행요건
③ 발행한도 | ③ 발행한도
존속기간 | 발행 후 최대 10년 한도로 유 효 기간을 정관에 규정
의결권 수 | 1 주당 최대 10개 한도로 기업이 정관에 규정
④ 절차・방법(정관변경→주총결의) | ④ 절차・방법(정관변경→주총결의)

=== 청크 14 (653자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=14 | label=table | table_id=8
[표] p.14 table_8
항 목 | 내 용
기 타 | 허위 또는 부정한 방법 으로 발행 시 그 발행일에 보통주식 발행으로 간주
⑥ 복수의결권 행사 제한 | ⑥ 복수의결권 행사 제한
⑦ 특례 | ⑦ 특례
벤처기업이 었던 기업의 특 례 | 벤처기업의 지위를 상실하는 경우에도 유효 * 중소기업의 범 위를 넘 어서 면 서 벤처기업의 지위를 상 실 하는 경우에도 유 효
공개매수 및 주식 대 량 보유 보고 특 례 | 복수의결권 발행 벤처기업은 자본시장법상 공개매수 및 대량보유 보고 시 의결권 기준 으로 적용
⑧ 발행의 보고 및 고시 | ⑧ 발행의 보고 및 고시
발행보고 | 복수의결권 발행내용 및 중요사항 변경시 중소벤처기업부에 보고
본점 등 공시 | 복수의결권 발행기업은 복수의결권주식 발행 내역 등을 본점과 지점에 비치 및 공시
관보고시 | 중소벤처기업부는 복수의결권 발행기업 명 단 , 주요사항 변경 등을 관보에 고시
⑨ 허위발행죄 및 과태료 | ⑨ 허위발행죄 및 과태료
위반행위 인지 ‧ 신고 | 중소벤처기업부는 규정에 위반한 혐 의가 있을 경우 직권으로 조사 , 누 구든지 위반한 사 실 이 있다고 인정할 때 에 중소벤처기업부에 신고
허 위발행 죄 | 허 위 또 는 부정한 방법으로 복수의결권 발행한 자는 10 년 이하 징 역 또 는 5 천 만원 이하 벌 금

=== 청크 15 (368자) ===
[meta] section_path=Ⅲ . 사업 추진내용 > 3 복수의결권 추진내용 > □ 복수의결권주식 제도 요약 | page=15 | label=list_item | table_id=
□ ( 비상장 벤처기업 ) 복수의결권주식 발행보고 前 비상장 벤처기업 여부 확인 , 요건 충족 기업만 가능
( 비상장 ) 복수의결권주식 발행보고 기업 법인등록 번호 조회
-대기업기업 집 단 계 열 회사 편 입 여부 ( 데이터포 털 연계 )
( 벤처확인 ) 복수의결권주식 발행보고 기업 사업자등록 번호 , 법인등록 번 호 , 벤처확인발 급번호 조회
-( 벤처확인 프로세스 ) 벤처확인 재확인  , 또 는 취소  ( 청문절차 ), 재발 급  등 복수의결권주식 발행 신고 가능 여부 체 크
-주주 총 회 결의 시 벤처확인이 유 효 하다 면 신청 가능
□ ( 복수의결권주식 기능개선 ) 복수의결권주식 발행보고 출력 기능개선 , 기 업 My 페 이지 활 동 이력

=== 청크 16 (581자) ===
[meta] section_path=Ⅲ . 사업 추진내용 > 3 복수의결권 추진내용 > □ 복수의결권주식 제도 요약 > < My페이지 기업 활동이력 예시 > | page=15 | label=section_header | table_id=
## < My페이지 기업 활동이력 예시 > (p.15)
① 벤처확인 이력 기준 복수의결권주식 발행보고 , 스톡옵션 신고 이력이 있는 경우 노 출
-벤처확인 유 효 시작일 ~ 만 료 일 기간 내 정관개정을 통한 복수의결권주식 발행보고 , 스톡옵션 신고 가 능
-이상 : 대기업 집 단계 열편 입 , 상장 , 폐 업 / 휴 업 등이 있는 경우 표시
② 벤처확인이력 기준 복수의결권주식 발행보고는 '23.11.17 부터 가능 , 스톡옵션은 98 년부터 신고 가능
-사용자 활 동이력은 업무시스템에 동일하게 노 출되도록 구 현
③ 벤처확인발 급번호 , 복수의결권주식 접수 번호 , 스톡옵션 접수 번호 기준 출력 기능개발
( 정관변경 ) 특별결의를 통한 변경 정관 업로 드 기능 구 현
※ 엄 격한 주주동의 , 발행주식 총 수의 4 분 의 3 이상 동의로 가결
특수관계인으로부터 받 은 투 자를 제 외 한 투 자금액이 누 적 100 억원 & 마 지 막 50 억원 이상
벤처확인 정보 연동을 통한 사용자 정보 입력 간소화
제출서류 업로 드 기능 구 현 ( 제출서류 이력 관리 기능 포함 )
< 복수의결권주식 ( 발행 , 변경 ) 필 수 기재 항목 >

=== 청크 17 (848자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=16 | label=table | table_id=10
[표] p.16 table_10
구 분 | 항 목 | 설 명
업무 담 당자 | 접수 번호 | 복수의결권주식 고유 접수 번호
업무 담 당자 | 접수일자 | 복수의결권주식 발행 접수일자
업무 담 당자 | 처리일 | 복수의결권주식 발행 승 인 처리일자
업무 담 당자 | 처리기간 | 복수의결권주식 발행 절차 소요기간
복수의결권주식 보고자 | 업체 명 | 벤처확인서 정보 연동
| 대표자 | 벤처확인서 정보 연동
| 사업자등록 번호 | 벤처확인서 정보 연동 및 조회
| 법인등록 번호 | 벤처확인서 정보 연동 및 조회
| 벤처기업확인서 발 급번호 | 벤처확인서 정보 연동 및 조회
| 전화 번호 | 회사 대표 연 락 처
| 전자우 편 | 보고자 전자우 편
| 소재지 | 벤처확인서 정보 연동 또 는 수기 입력
| 복수의결권주식을 받 은자의 성 명 및 발행 수 량 | 창업주 , 공동창업주 선택을 통한 성 명 , 발행 수 량 기 재
| 복수의결권주식의 발행일자 |
| 복수의결권주식의 의결권 수 창업주 보유 보통주 납 입 여부 |
| 전 환 일자 | 복수의결권주식이 보통주로 전 환 된 경우 기재
| 전 환 사유 | 복수의결권주식이 보통주로 전 환 된 경우 기재
| 투 자일자 | 복수 입력 가능
| 투 자유치금액 ( 특수관계인 포함 ) | 복수 입력 가능
| 투 자유치금액 ( 특수 관계인 제 외 ) | 복수 입력 가능
| 투 자 전 창업주 지 분율 | 복수 입력 가능
| 투 자 후 창업주 지 분율 | 복수 입력 가능
| 합계 | 투 자유치금액 및 투 자 후 창업주 지 분율
| 복수의결권주식 발행 , 변경 | 발행 , 변경에 따 른 접수 번호 별도 관리
| 보고서 제출 년 / 월 / 일 | 보고서 신청일자 = 접수일자

=== 청크 18 (334자) ===
[meta] section_path=Ⅲ . 사업 추진내용 > 3 복수의결권 추진내용 > □ 복수의결권주식 제도 요약 > < My페이지 기업 활동이력 예시 > | page=17 | label=list_item | table_id=
※ 복수의결권주식 ( 발행 , 주요사항 변경 ) 보고서 양 식 제공 , 보고서 양 식 분석 을 통 환 시스템 화 면 기 획 필 요
< 사 후 변경에 따 른 복수의결권주식의 보통주 전 환 >
□ ( 복수의결권주식 발행보고 ) 복수의결권주식 받 은 자의 성 명 , 발행일자 , 발행 수 량 을 벤처확인종합관리시스템 공시
복수의결권주식 발행보고 서 문서 출력 기능 구 현
「 벤처기업육성에 관한 특별조치법 시행규칙 」 별지 제 9 호 참 고
복수의결권주식 변경보고 서 문서 출력 기능 구 현
-변경 신고 완 료 후 복수의결권 발행 변경 전 / 후 비교 정보 출력
복수의결권주식 변경사항 공시 기능 구 현

=== 청크 19 (82자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=17 | label=table | table_id=11
[표] p.17 table_11
보고인 성 명 | 복수의결권주식 발행 신청인의 휴 대 폰 인 증 정보
서 명 |
첨 부 파 일 | 제출된 첨 부서류

=== 청크 20 (156자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=17 | label=table | table_id=12
[표] p.17 table_12
사 후 변경의 유 형 | 전환 여부
상 속 또는 양 도 |
창업주의 이사 사 임 | 즉 시 전환
공시대상기업 집단 포함 |
상장 | 상장 후 최대 3년 까 지 유 효
벤처기업 지위 상실 | 이미 발행된 복수의결권주식 존속 기한 까 지 계 속 유 효

=== 청크 21 (730자) ===
[meta] section_path=Ⅲ . 사업 추진내용 > 3 복수의결권 추진내용 > □ 복수의결권주식 제도 요약 > < My페이지 기업 활동이력 예시 > | page=18 | label=list_item | table_id=
□ ( 복수의결권 위 반 ( 허위 거짓 ) 발행 신고기능 ) 복수의결권주식 발행 위반행 위 신고기능 구 현
개인정보 수 집 및 이용 동의 절차 기능 구 현 , 신고자 통신사 인 증
-위반행위 신고작성 방법 안내 페 이지 구

## 4 스톡옵션 추진내용 (p.19)
□ ( 데이터 이관 ) 중소벤처 24 內 벤처기업 스톡옵션 ( 주식매수선택권 ) 신고를 위해 가입된 회원정보 * 및 과거 각 종 데이터 / 문서 이관
벤처확인종합관리시스템 內 탑 재를 위한 회원 중복가입 등 데이터 검 증 ( 회원통합 )
신고접수 및 보완요청 , 최종수리 단계별 신고자 알림
스톡옵션 신고 물량 배정 기능 구축 ( 중소벤처기업부 지방청 )
벤처기업법 제 16 조의 3 비상장 벤처기업 확인
-주주 총 회 결의 시 벤처확인이 유 효 하다 면 신청 가능 , 과거 벤처확인이
력이 있는 경우 해당 유 효 기간 내 주주종회 결의시 신청 가능
☞ ( 기능 구축 ) 대민사이트 스톡옵션 신고 前 증 권시장 ( 유가 증 권시장 , 코 스 탁 시장 , 코넥 스시장 ) 에 상장되지 않 은 비상장 벤처기업 여부 확인
< 비상장 벤처기업 여부 조회(안) >

## 1안) 비상장 / 벤처기업 동시 조회 (p.20)
2안) 벤처기업 조회 / 비상장 별도 확인
연도별 행사가격 분 포
-배정 조건 外 부득이 재배정 이 슈 가 발행할 수 있 음 , 부여신고 접수 번호 를 통한 재배정 이력 조회 기능 구축 ( 지방청 배정 이력 전체 조회 가 능 )

=== 청크 22 (1145자) ===
[meta] section_path=Ⅲ . 사업 추진내용 > 4 스톡옵션 추진내용 > □ 스톡옵션 부여신고 | page=21 | label=section_header | table_id=
## □ 스톡옵션 부여신고 (p.21)
비상장 벤처기업 조회 후 스톡옵션 부여 신고서 작성 기능 구 현
( 출력 ) 「 벤처기업육성에 관한 특별조치법 시행규칙 」 별지 제 3~4 호 참 고
※ ( 중요 ) 기재된 화 면 은 참 고자 료 이며 , 별도 화 면 기 획 및 제안 진행
NOE5
기업정보 , 업무 담 당자 입력 간소화 방안 기 획
기업 명 , 대표자 명 등 일반적인 입력정보
사업자등록 번호 , 벤처확인발 급번호 등을 통한 주식 매수선택권 부여 신고 가능 조회기능 탑 재 3. 벤처확인정보 연계
벤처확인발 급번호 , 벤처확인일 , 유 효 시간
※ 벤처확인이력조회가 되지 않 는 경우 문의 case1. 벤처확인만 료 case2. 사업자등록 번호 와 벤처확인정보 불 일치 case3. 벤처확인만 료 일 기준 벤처재확인 프로 세 스 진행 中
부여주식종류 별도 코드 로 관리
액 면 가 단위 ( 원 ), 숫 자한 글 정보 표기
부여인원 주식수 , 행사가격 총 합과 동일해야 함
olue
50(22492482(8102)
0184 522
OPA84 2191
92 4 849
1. 1841219391 842(2 48165 913 4818 12)|
2.78084 28898 325 1( 4 16593 4 18 22)|
3. (992 087712(3 (4816593 4818 39)
정관에 ' 스톡옵션 ( 주식매수선택권 ) 주식의 행사기간 ' 이 규정되어 있는지 여부 中 행사기간은 주식매수 선택권 부여 결의사항 행사기간과 연동되어 체 크 되 어야 함
주주 총 회특별결의 , 이사회 결의에 따 른 입력창 , 페 이지부터 임시 저 장 기능 활 성화
(+) 연 번 추가를 통한 부여인원 등록 , 부여인원 대 량 등록기능 개발
부여인원의 핸드폰번호 등록 ( 개인정보보 호 에 관한 신고자 대리 등록에 따 른 등록 동의 )
핸드폰번호 를 통해 부여된 인원의 부여주식 정보 안내
자격 , 부여방법 코드값 으로 관리 ,
부여인원 주식 총 합 자동 계산
항목별 첨 부 파 일 업로 드 복수
4 91091 71909 942( 48163593 4818 42)
49 49
40 9 28
438s
R3E 049
4400-248409-8948
VOZAN
243500 B73E
WOST
MOFNO
080389948 483
RADOLA 2891 9940R 49(EMES
NHEE

=== 청크 23 (260자) ===
[meta] section_path=Ⅲ . 사업 추진내용 > 4 스톡옵션 추진내용 > □ 스톡옵션 취 소 ( 부분 )/ 철 회 신고 | page=22 | label=section_header | table_id=
## □ 스톡옵션 취 소 ( 부분 )/ 철 회 신고 (p.22)
스톡옵션 부여 신고 건에 대한 주식매수선택권 피 부여자 ( 부 분 ) 취소 , 철회 기능
( 부 분 ) 취소 , 철회 신고 통보 결과 기능 구 현
-피 부여자 취소 및 철회 신고 사항 알림 기능 구 현

## □ 스톡옵션 부여대상자 (p.23)
부여대상자는 시스템 로 그 인 후 My 페 이지를 통해 스톡옵션 부여 현황 및 행사 정보 확인

## < My페이지 스톡옵션 부여대상자 예시 > (p.23)

=== 청크 24 (37자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=23 | label=table | table_id=13
[표] p.23 table_13
스톡옵션 | 부여주식 | 주식 행사

=== 청크 25 (414자) ===
[meta] section_path=Ⅳ . 제안요청 내용 | page=24 | label=section_header | table_id=
## Ⅳ . 제안요청 내용 (p.24)

## 1 과업수행방법 (p.24)

## □ 과업 착 수 (p.24)
본 시스템 기능 고도화 용역사업은 과업 시작일로부터 10 일 이내 착 수하 여야 함
계약상대자는 계약체결일로부터 10 일 이내 다 음 과 같 은 서류를 벤처확 인기관에 문서로 제출해야 함
∨ 착 수계
∨ 책 임기술자 선임계
∨ 책 임기술자 이력서 및 기술자격 증 사본
∨ 참 여기술자 이력서 및 기술자격 증 사본
∨ 보안 각 서 및 보안대 책
∨ 과업수행계 획 서
∨ 기타 필 요사항

## □ 과업수행계 획 서 제출 (p.24)
( 과업수행계 획 서 ) 계약서 , 과업내용서 등의 내용을 근거로 작성
( 계 획승 인 ) 계약상대자는 과업수행계 획 서를 벤처기업확인기관의 승 인을 득 한 후 이에 따라 과업 수행
제 출서류 목 록

=== 청크 26 (606자) ===
[meta] section_path=Ⅳ . 제안요청 내용 > 2 제안요청 일반사항 | page=25 | label=section_header | table_id=
## 2 제안요청 일반사항 (p.25)
□ 제안 업체는 시스템 기능 고도화 완 료 후 기능 확장성 등을 고 려 하여 제안하여야 함
□ 제안 업체는 제안하는 모든 부 분 에 포 괄 적인 책 임을 가지며 , 제안 시점 에서 사업수행요건 미충족 업체는 선정 대상에서 제 외 함
□ 제안규격의 만족 여부는 벤처기업확인기관에서 제시하는 평가 기준 등 에 의해 심 사함
□ 전산시스템 운용 및 유지관리에 대처할 수 있는 구체적 기술이전 , 교육 계 획 및 지원계 획 을 제시해야 함
□ 특별한 사유가 없 는 한 본 시스템 기능 고도화사업은 사업 기간 中 개 발 완 료 및 테 스트 가능하여야 하며 , 하자 보 증 기간 내 하자보수 및 유 지관리 계약이행에 대한 모든 책 임을 져 야 함
□ 안정적이고 확장 가능한 최적의 시스템 개발하며 개발업무의 각 종 서식 및 코드 , 시스템 간 통합 및 연계 , 전산 망 간 연계 등 정보화 표준을 준용하여 개발해야 함
□ 시스템 개발과정에서 취득한 일체 모든 정보는 외 부로 유출 또 는 발 설 해서는 안 되며 , 만약 사업 과정에서 보안사고 발 생 시 업체에서는 일 체 민 형 사상의 책 임을 지고 , 벤처기업확인기관이 입은 손 해에 대하여 배상해야 함

=== 청크 27 (700자) ===
[meta] section_path=Ⅳ . 제안요청 내용 > 3 제안요청 필 수사항 | page=26 | label=section_header | table_id=
## 3 제안요청 필 수사항 (p.26)
□ ① 보안성을 고 려 한 시스템 구성 및 운영방안 , ② 보안성 강 화 및 관리의 용이성을 위한 추가지원 가능 사항 ( 필 요시 ) 을 제시해야 함
□ 시스템 장 애 발 생 시 , 즉각 복구할 수 있는 체제를 구축해야 함
□ 향 후 시스템 확장성을 위해 시스템 기능 고도화 관련 표준을 최대한 준수
□ 제안서에 기재되지 않 은 사항이라 할지라도 제품성능에 필 요한 사항은 벤처기업확인기관과 협의를 통해 공 급 ( 납 품 ) 하여야 함
□ 최종 인수 결과 시스템 운영 불 가로 ' 계약조건 미충족 ' 으로 판 단 시 , 벤 처기업확인기관의 요구에 의해 구축한 모든 시스템을 철거 · 회수하여야 하며 , 그 비용은 제안업체에서 일체 부 담 하고 이로 인한 벤처기업확인 기관의 손 해를 배상해야 함
□ 본 과업의 시스템은 유기적으로 데이터 교 환 이 가능하여야 하며 , 타 기관 의 시스템 연계가 가능해야 함
□ 시스템 기능 고도화 과정에서 취득한 정보에 대한 보안 관리 방법 등에 대한 제시 및 시스템 구축 후 하자보수를 위한 방안을 제시해야 함

## □ 요구사항 정의표 (p.27)
※ 사업 내용이 변경 될 경우 과업변경절차에 따라 상 호 협의하여 결정하며 , 제안서 작성 시 제안요청서 요구사 항에 명 시되지 않았 으나 제안 업체 판 단으로 추가되어야 할 요구사항에 대해서는 별도 표시하여 추가 작성 가능함

=== 청크 28 (667자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=27 | label=table | table_id=14
[표] p.27 table_14
분 류 기준 | 세부 내용 | 요구 사항수
기능 요구사항 (SFR, System Function Requirement) | - 목표시스템이 반 드 시 수행하여야 하거나 목표 시스템을 이용하여 사용자가 반 드 시 수행할 수 있어야 하는 기능 ( 동작 ) 에 대하여 기술 | 38
시스템장비구성 요구사항 (ECR, Equipment Composition Requirement) | - 목표 사업 수행을 위해 필 요한 하 드 웨어 , 소프트 웨어 , 네 트 워크 등의 도입 장비 내역 등 시스템 장비 구성에 대한 요구사항을 기술 | 5
보안 요구사항 (SER,Security Requirement) | - 정보 자산의 기 밀 성과 무결성을 확보하기 위해 목표시스템의 데이터 및 기능 , 운영 접근을 통 제하기 위한 요구사항을 기술 | 9
프로 젝 트 관리 요구사항 (PMR, Project Management Requirement) | - 프로 젝 트의 원 활 한 수행을 위한 관리 방법 및 추진 단계별 수행방안에 대한 요구사항을 기술 | 10
프로 젝 트 지원 요구사항 (PSR, Project Support Requirement) | - 프로 젝 트의 원 활 한 수행을 위해 필 요한 지원 사항 및 방안에 대한 요구사항을 기술 | 9
합 계 | 합 계 | 113

=== 청크 29 (78자) ===
[meta] section_path=Ⅳ . 제안요청 내용 > 3 제안요청 필 수사항 > □ 요구사항 상세 | page=28 | label=section_header | table_id=
## □ 요구사항 상세 (p.28)

## 가 기능 요구사항(Sy s te m Fu nction R e qu ire m ent) (p.28)

=== 청크 30 (169자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=28 | label=table | table_id=15
[표] p.28 table_15
요구사항 고유 번호 | 요구사항 고유 번호 | SFR-001
요구사항 명 칭 | 요구사항 명 칭 | 사용자 인 증 기능 구 현
요구사항 상세설명 | 정의 | 시스템 기업 / 사용자 인 증 기능 구 현
산 출 | 정보 | 요구사항정의서 , 프로 그램명세 서 , 개발산출 물

=== 청크 31 (152자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=28 | label=table | table_id=16
[표] p.28 table_16
요구사항 고유 번호 | 요구사항 고유 번호 | SFR-002
요구사항 명 칭 | 요구사항 명 칭 | 회원가입
요구사항 상세설명 | 정의 | 벤처확인종합관리시스템 회원통합
산 출 | 정보 | 요구사항정의서 , 프로 그램명세 서 , 개발산출 물

=== 청크 32 (164자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=28 | label=table | table_id=17
[표] p.28 table_17
요구사항 고유 번호 | | SFR-003
요구사항 명 칭 | 요구사항 명 칭 | 중소기업확인서
요구사항 상세설명 | 정의 | 복수의결권주식 발행보고 및 스톡옵션 부여신고 前 중소기업여부 확인
산 출 | 정보 | 요구사항정의서 , 프로 그램명세 서 , 개발산출 물

=== 청크 33 (168자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=28 | label=table | table_id=18
[표] p.28 table_18
요구사항 고유 번호 | SFR-004
요구사항 분 류 | 기능 요구사항
요구사항 명 칭 | 비상장 여부 조회
요구사항 상세설명 정의 | 복수의결권주식 발행보고 및 스톡옵션 부여신고 前 비상장 여부 조회
산 출 정보 | 요구사항정의서 , 프로 그램명세 서 , 개발산출 물

=== 청크 34 (178자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=29 | label=table | table_id=19
[표] p.29 table_19
요구사항 고유 번호 | 요구사항 고유 번호 | SFR-005
요구사항 명 칭 | 요구사항 명 칭 | 벤처기업 여부 조회
요구사항 상세설명 | 정의 | 복수의결권주식 발행보고 및 스톡옵션 부여신고 前 벤처확인정보 연동
산 출 | 정보 | 요구사항정의서 , 프로 그램명세 서 , 개발산출 물

=== 청크 35 (164자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=29 | label=table | table_id=20
[표] p.29 table_20
요구사항 고유 번호 | | SFR-006
요구사항 명 칭 | 요구사항 명 칭 | 요건 조회 확인 Dashboard
요구사항 상세설명 | 정의 | 복수의결권 , 스톡옵션 요건 가능 여부를 공개
산 출 | 정보 | 요구사항정의서 , 프로 그램명세 서 , 개발산출 물

=== 청크 36 (175자) ===
[meta] section_path=Ⅶ . 별지서식 및 붙임 > 2024 년 벤처확인종합관리시스템 기능 고도화 용역사업 > 소프트웨어 보안약점 기준 1) > 자에게 데이터 누 출이 가능해지는 보안약점 | page=29 | label=table | table_id=21
[표] p.29 table_21
요구사항 고유 번호 | 요구사항 고유 번호 | SFR-007

In [3]:
import os
from pathlib import Path
import json, re, unicodedata
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from dotenv import load_dotenv, find_dotenv
from openai import OpenAI
from sentence_transformers import SentenceTransformer

from preprocess.pp_basic import docs, BASE_DIR, EVAL_DIR, GOLD_EVIDENCE_CSV, GOLD_FIELDS_JSONL
from preprocess.rag_experiment import (
    CONFIG, ExperimentSpec, load_questions_df, make_components, RAGExperiment
)

# .env 로드(override=True로 커널 환경에 확실히 반영)
dotenv_path = find_dotenv(usecwd=True) or str(BASE_DIR / ".env")
load_dotenv(dotenv_path, override=True)
api_key = (os.getenv("OPENAI_API_KEY") or "").strip().strip('"').strip("'")
if not api_key:
    raise RuntimeError("OPENAI_API_KEY가 비어 있습니다. .env 값을 확인한 뒤 커널을 재시작하세요.")

client = OpenAI(api_key=api_key)

# embed 모델은 커널에서 1번만 로드(중요)
embed_model = SentenceTransformer("nlpai-lab/KoE5")

# gold 로드
def load_gold_evidence(path):
    """CSV를 우선 사용. 파싱 실패 시에만 JSONL fallback."""
    try:
        return pd.read_csv(path, encoding="utf-8-sig")
    except Exception as e:
        print(f"[warn] gold_evidence.csv parse failed: {e}")
        jpath = Path(path).with_suffix(".jsonl")
        if not jpath.exists():
            raise
        rows = []
        with open(jpath, "r", encoding="utf-8-sig", errors="replace") as f:
            for line in f:
                if line.strip():
                    rows.append(json.loads(line))
        return pd.DataFrame(rows)

gold_evidence_df = load_gold_evidence(GOLD_EVIDENCE_CSV)

def load_gold_fields_jsonl(path):
    rows = []
    with open(path, "r", encoding="utf-8-sig", errors="replace") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    out = []
    for r in rows:
        iid = r["instance_id"]
        doc_id = r.get("doc_id", "")
        fields = r.get("fields", {}) or {}
        for k, v in fields.items():
            out.append({"instance_id": iid, "doc_id": doc_id, "field": k, "gold": v})
    return pd.DataFrame(out)

gold_fields_df = load_gold_fields_jsonl(GOLD_FIELDS_JSONL)
questions_df = load_questions_df()

print("gold_evidence_df:", gold_evidence_df.shape)
print("gold_fields_df:", gold_fields_df.shape)
print("questions_df:", questions_df.shape)
print("n_docs:", len(docs))

gold_evidence_df: (402, 5)
gold_fields_df: (420, 4)
questions_df: (211, 5)
n_docs: 100

In [4]:
# 평가 문서 필터(커널당 1회)
def name_key(s: str) -> str:
    s = unicodedata.normalize("NFC", str(s)).strip()
    s = unicodedata.normalize("NFKC", s)
    s = re.sub(r"\s+", " ", s)
    return s

gold_doc_key_set = set(name_key(x) for x in gold_fields_df["doc_id"].astype(str).unique())
EVAL_DOCS = [p for p in docs if name_key(p.name) in gold_doc_key_set]

print("Eval docs:", len(EVAL_DOCS))

Eval docs: 20

### 실험 ID 변경

In [5]:
RUN_EXP_ID = 3   # 1~24
N_DOCS = None       # 디버깅은 1~5 추천, 전체는 None

# N개 문서 또는 전체 문서 테스트
# RUN_DOCS = EVAL_DOCS[:N_DOCS]
RUN_DOCS = EVAL_DOCS

SPECS = {
    1:  ("C1","R1","G1"),  2:  ("C1","R1","G2"),
    3:  ("C1","R2","G1"),  4:  ("C1","R2","G2"),
    5:  ("C1","R3","G1"),  6:  ("C1","R3","G2"),
    7:  ("C2","R1","G1"),  8:  ("C2","R1","G2"),
    9:  ("C2","R2","G1"),  10: ("C2","R2","G2"),
    11: ("C2","R3","G1"),  12: ("C2","R3","G2"),
    13: ("C3","R1","G1"),  14: ("C3","R1","G2"),
    15: ("C3","R2","G1"),  16: ("C3","R2","G2"),
    17: ("C3","R3","G1"),  18: ("C3","R3","G2"),
    19: ("C4","R1","G1"),  20: ("C4","R1","G2"),
    21: ("C4","R2","G1"),  22: ("C4","R2","G2"),
    23: ("C4","R3","G1"),  24: ("C4","R3","G2"),
}

c, r, g = SPECS[RUN_EXP_ID]
spec = ExperimentSpec(exp_id=RUN_EXP_ID, chunker=c, retriever=r, generator=g)
print("Running spec:", spec)
print("RUN_DOCS:", len(RUN_DOCS))

# exp별 최적 k 자동 적용 (없으면 기본값)
BEST_K_BY_EXP = {
    3: (24, 8),
    21: (20, 6),
}

CONFIG["chunk_length"] = 800
CONFIG["alpha"] = 0.7
CONFIG["max_context_chars_per_question"] = 3000
CONFIG["target_field_max_context_chars"] = 2200

rk, ck = BEST_K_BY_EXP.get(
    RUN_EXP_ID,
    (int(CONFIG.get("retrieve_k", 24)), int(CONFIG.get("context_k", 8)))
)
CONFIG["retrieve_k"] = int(rk)
CONFIG["context_k"] = int(min(ck, rk))
CONFIG["top_k"] = CONFIG["retrieve_k"]  # backward compatibility

print(f"Applied k => retrieve_k={CONFIG['retrieve_k']}, context_k={CONFIG['context_k']}")

Running spec: ExperimentSpec(exp_id=3, chunker='C1', retriever='R2', generator='G1')
RUN_DOCS: 20
Applied k => retrieve_k=24, context_k=8

### 디버깅 사전 설정(선택)

In [6]:
# (옵션) sentinel 모니터링용
SENT_NOT_FOUND = "NOT_FOUND"
SENT_GEN_FAIL = "GEN_FAIL"

def count_sentinels(pred_map: dict) -> dict:
    if not isinstance(pred_map, dict):
        return {"n_keys": 0, "n_not_found": 0, "n_gen_fail": 0}

    vals = [str(v).strip() for v in pred_map.values()]
    vals_l = [v.lower() for v in vals]

    n_nf = sum(v in {"not_found", "notfound"} for v in vals_l)
    n_gf = sum(v == "gen_fail" for v in vals_l)
    return {"n_keys": len(vals), "n_not_found": n_nf, "n_gen_fail": n_gf}

### 실험 수행 및 결과 저장

In [7]:
chunker, retriever, generator = make_components(spec, embed_model=embed_model, client=client)
rag = RAGExperiment(chunker=chunker, retriever=retriever, generator=generator, questions_df=questions_df)

rows = []
for doc_path in tqdm(RUN_DOCS, desc=f"Exp {spec.exp_id} docs"):
    m = rag.run_single_doc_metrics_singleq(
        doc_path,
        gold_fields_df=gold_fields_df,
        gold_evidence_df=gold_evidence_df,
        top_k=CONFIG["top_k"],
        sim_threshold=80,
    )
    m["exp_id"] = spec.exp_id
    m["chunker"] = spec.chunker
    m["retriever"] = spec.retriever
    m["generator"] = spec.generator
    rows.append(m)

doc_df = pd.DataFrame(rows)

# exp-level average
metric_cols = ["ret_recall","ret_mrr","hit_rank_mean","hit_r1_ratio","hit_r2_ratio","hit_r1_r2_ratio","gen_fill","gen_match","gen_sim","gen_match_strict","gen_strict_coverage"]
metric_cols = [c for c in metric_cols if c in doc_df.columns]
avg = doc_df[metric_cols].mean(numeric_only=True)
exp_df = pd.DataFrame([{
    "exp_id": spec.exp_id,
    "chunk": spec.chunker,
    "retriever": spec.retriever,
    "model": spec.generator,
    "n_docs": len(doc_df),
    **{k: float(avg[k]) for k in avg.index},
}])

display(exp_df.round(4))

out_dir = BASE_DIR / "outputs"
out_dir.mkdir(parents=True, exist_ok=True)

exp_out = out_dir / f"exp{spec.exp_id:02d}_explevel.csv"
exp_df.to_csv(exp_out, index=False, encoding="utf-8-sig")
print("Saved:", exp_out)

Exp 3 docs: 100%|██████████| 20/20 [11:04<00:00, 33.23s/it]

,exp_id,chunk,retriever,model,n_docs,ret_recall,ret_mrr,hit_rank_mean,hit_r1_ratio,hit_r2_ratio,hit_r1_r2_ratio,gen_fill,gen_match,gen_sim,gen_match_strict,gen_strict_coverage
0,3,C1,R2,G1,20,0.9636,0.7171,2.4832,0.5955,0.15,0.7455,0.9364,0.4636,61.4207,0.9,0.1727

Saved: /Users/won/dev/00_codeit/0_mission/200_DL_RAG/outputs/exp03_explevel.csv

In [8]:
## 인덱스 입력(청크) 점검: ALL_DATA 사용 여부 + 샘플 출력
CHECK_DOCS = RUN_DOCS[:10] if len(RUN_DOCS) > 10 else RUN_DOCS

from preprocess import pp_v5 as pp5

rows = []
for doc in CHECK_DOCS:
    chunks_alldata = pp5.chunk_from_alldata(doc.name, size=CONFIG["chunk_length"])
    used_alldata = chunks_alldata is not None

    # 실험에서 실제로 인덱스에 넣는 청크(=현재 spec의 chunker 결과)
    chunks_for_index = chunker.chunk(doc)

    rows.append({
        "doc": doc.name,
        "used_alldata": used_alldata,
        "n_chunks_for_index": len(chunks_for_index),
        "n_table_chunks_for_index": sum("[표]" in c for c in chunks_for_index),
        "first_chunk_head": (chunks_for_index[0][:120] if chunks_for_index else "")
    })

audit_df = pd.DataFrame(rows)
display(audit_df[["doc", "used_alldata", "n_chunks_for_index", "n_table_chunks_for_index"]])

print("\n요약")
print("- 점검 문서 수:", len(audit_df))
print("- ALL_DATA 사용 문서 수:", int(audit_df["used_alldata"].sum()))
print("- ALL_DATA 미사용 문서 수:", int((~audit_df["used_alldata"]).sum()))

if (~audit_df["used_alldata"]).any():
    print("\nALL_DATA 미사용 문서(=fallback 가능성):")
    for name in audit_df.loc[~audit_df["used_alldata"], "doc"].tolist():
        print("  -", name)

# 샘플 문서 하나의 실제 인덱스 입력 청크 미리보기
sample_doc = CHECK_DOCS[0]
sample_chunks = chunker.chunk(sample_doc)
print("\n샘플 문서:", sample_doc.name)
print("샘플 청크 수:", len(sample_chunks), "| 표 포함 청크 수:", sum("[표]" in c for c in sample_chunks))
for i, ch in enumerate(sample_chunks):
    print(f"\n=== index chunk {i} ({len(ch)}자) ===")
    print(ch)

,doc,used_alldata,n_chunks_for_index,n_table_chunks_for_index
0,(사)벤처기업협회_2024년 벤처확인종합ᄀ...,True,130,0
1,(사)부산국제영화제_2024년 BIFF & ACFM 온ᄅ...,True,64,0
2,(사）한국대학스포츠협의회_KUSF 체육특기자...,True,93,0
3,(재)예술경영지원센터_통합 정보시스템 ...,True,54,0
4,2025 구미 아시아육상경기선수권대회 조직ᄋ...,True,59,0
5,경기도 안양시_호계체육관 배드민턴장 미...,True,80,0
6,경기도 평택시_2024년도 평택시 버스정보ᄉ...,True,106,0
7,경기도사회서비스원_2024년 통합사회정보시...,True,89,0
8,경상북도 봉화군_봉화군 재난통합관리...,True,73,0
9,경희대학교_[입찰공고] 산학협력단 정...,True,56,0

요약
- 점검 문서 수: 10
- ALL_DATA 사용 문서 수: 10
- ALL_DATA 미사용 문서 수: 0

샘플 문서: (사)벤처기업협회_2024년 벤처확인종합관리시스템 기능 고도화 용역사업 .pdf
샘플 청크 수: 130 | 표 포함 청크 수: 0

=== index chunk 0 (800자) ===
용역사업
- (복수의결권주식, 스톡옵션, 성과조건부주식) -

2024. 03.
목 차
1. 추진개요 3
2. 추진방안 5
3. 추진내용 9
4. 제안요청내용 24
5. 입찰관련사항 78
6. 제안서작성요령 82
7. 별지서식 및 붙임 94
Ⅰ. 추진개요
1 추진배경 및 방향
□ 「벤처기업육성에 관한 특별조치법」(이하 ‘벤처기업법’) 복수의결권주식, 스톡옵
션(주식매수선택권), 성과조건부주식교부계약(RS) 등의 기능 고도화 및 이관,
신규 구축업무를 本 과업에서 추진
⚬ (복수의결권주식*) 벤처기업법 제16조의11에 따라 발행된 복수의결권주
식 보고 업무처리 시스템 구축
* 복수의결권이란? 모든 주주는 1주당 하나의 의결권을 갖는 주주평등원칙(상법)과 별도로
비상장 벤처기업 창업자에게만 1주당 최대 10배의 의결권 행사를 부여하는 제도
⚬ (스톡옵션*) 벤처기업법 제16조의3에 따라 부여된 벤처기업 스톡옵션
부여, 취소·철회 신고 및 업무시스템 구축
* 스톡옵션이란? 비상장 벤처기업 임·직원 및 기업 성장에 기여한 자에게 미리 정한 가격(행
사가격)으로 신주를 인수하거나 자기의 주식을 매수할 수 있는 권리 혹은 주식의 시가와 행
사가격의 차액을 청구할 수 있는 권리를 부여하는 제도
- 중소벤처24 內 스톡옵션 신청 기능 이관을 추진하며, 과거 데이터 정
제 및 적재 등을 통한 데이터 이관 추진
⚬ (성과조건부주식*) 벤처기업법 제16조의19에 따라 성과조건부주식교부
계약의 신고 및 업무처리 시스템 구축
* 성과조건부주식이란? 비상장 벤처기업 임ㆍ직원 및 특정인에게 자기주식 부여를 약속하되,
일정 재직기간 및

=== index chunk 1 (800자) ===
 조건을 충족해야 주식이 부여 대상자에게 귀속되도록 제한을 둔 주식
□ 복수의결권주식 발행 보고 및 스톡옵션 신고기능은 기존 시스템 내 벤
처확인 이력정보와 신고자(벤처기업)의 정보와 연동
- 3 -
2 사업개요
□ (사 업 명) 2024년 「벤처확인종합관리시스템 기능 고도화」 용역사업
- 복수의결권주식, 스톡옵션, 성과조건부주식교부 기능 구축 및 고도화
□ (사업기간) 계약일로부터 150일
* 1차 오픈 : 2024.07.10. 성과조건부 및 스톡옵션 오픈
** 2차 오픈 : 2024.09월 中 GrandOpen
□ (소요예산) 352,000,000원(부가가치세 포함)
□ (계약방식) 제한경쟁입찰(협상에 의한 계약)에 의한 선정*
* (근거) 「국가를 당사자로 하는 계약에 관한 법률」 시행령 제21조, 제43조
□ (선정 방법) 본 사업은 전문기술이 요구되는 사업으로 기술력이 높은 업체
를 선정하고 협상을 통해 요구사항을 반영할 수 있는 ’협상에 의한 계약’
방식으로 추진
◦ (선정 절차) 제안서 평가는 기술평가(90%)와 가격평가(10%)를 합산하여
종합평가점수로 산출(배정한도 85% 이상, 고득점순으로 협상적격자 결
정)
행정기관 및 공공기관 정보시스템 구축․운영 지침
제18조(평가배점)
행정기관 등의 장은 기술력이 우수한 사업자를 선정하여 정보화사업의 품질을 확보하기 위해
국가계약법 시행령 제43조의2, 지방계약법 시행령 제44조에 따라서 협상에 의한 계약체결 방법
을 우선적으로 적용하고, 기술능력평가 배점한도를 90점으로 한다.
□ (대기업 참여 제한) 「소프트웨어 진흥법」제48조제2항에 따라, 사업

=== index chunk 2 (800자) ===
금액
20억원 미만 계약은 대기업 참여 제한
- 4 -
Ⅱ. 사업 추진방안
1 추진목표
◈ 벤처확인 연계를 통한 복수의결권 및 스톡옵션 시스템 고도화
추진 ◈ 복수의결권주식, 스톡옵션 업무시스템 구축
목표 ◈ 스톡옵션 데이터 이관 작업 수행
◈ 신청접수 및 처리 결과 알림 One-Stop Service
추진과제 세부 실행내용
① 비상장 벤처확인기업 조회, 복수의결권주식 발행·변경 보고 고도화,
스톡옵션 부여, 취소·철회 신고기능 구축
② 단계별 처리 절차 준수
대민사이트
복수의결권주식 비상장 벤처기업 조회→보고(발행ㆍ변경)→접수(보완)→공시ㆍ고시
스톡옵션
비상장 벤처기업 조회→신고(취소 철회 포함)→접수(보완)
성과조건부 주식
③ 복수의결권(기업), 스톡옵션(기업, 부여대상자) 정보 확인 기능 구축
④ 감독기관 전용 시스템(복수의결권, 스톡옵션 별도)
BackOffice ⑤ 복수의결권주식, 스톡옵션 관리(본부, 13개 지방청) 기능
⑥ 복수의결권주식, 스톡옵션 통계 등
⑦ 타 기관 API연계를 통한 정보 확인
추가사항
⑧ 입력정보&서류제출 간소화, 정보보안 솔루션 적용
- 5 -
2 추진체계 및 역할
□ 추진체계
중소벤처기업부
벤처기업확인기관
(시스템 고도화 발주)
자문위원
(법률, 검수·검사 등)
사업 수행업체
벤처확인종합관리시스템 기능 고도화 수행
(복수의결권, 스톡옵션, 성과조건부주식)
운영 유지관리 업체
現 시스템 유지관리업무 수행 中
□ 추진역할
구 분 역 할
중소벤처기업부 ㆍ사업총괄 운영ㆍ관리 감독
ㆍ벤처확인제도 운영기관
ㆍ사업계획 수립, 제안요청서 작성
벤처기업확인기관
ㆍ사업관리 및 검사
ㆍ사업수

=== index chunk 3 (800자) ===
행 및 운영업무
자문위원 ㆍ시스템 구축 및 법률 자문 등
운영 유지관리 업체 ㆍ벤처확인종합관리시스템 운영 유지관리 업무 수행 中
ㆍ복수의결권주식 및 스톡옵션 시스템 기능 고도화 컨설팅
ㆍ사업수행에 필요한 데이터(스톡옵션) 자료 이관
사업 수행업체 ㆍ주요 기능 분석 및 인터뷰
ㆍ기획 및 디자인, 벤처확인종합관리시스템 연계 영향 평가
ㆍ복수의결권주식 및 스톡옵션 시스템 기능 고도화 및 테스트
- 6 -
3 추진방안
□ (구축 인터뷰) 복수의결권주식 및 스톡옵션 시스템 구축을 위한 사전 기능
요구사항에 대한 충분한 인터뷰* 진행, 분석ㆍ기획 보고서 제출
* 시스템 Risk-Point해결/개선을 위한 중소벤처기업부, 중소벤처기업부 지방청(13개) 미팅
□ (데이터분석) 스톡옵션 데이터분석을 통한 통계*자료 및 타 기관 연계정
보 현황 수요조사 진행
* 벤처기업유형별(① 벤처투자, ②연구개발, ③혁신성장, 그 외 과거유형) 연계를 통한 과
거 스톡옵션 신고 비율 및 업종, 지역, 매출 통계, 거래소상장 여부 등으로 활용
◦ 벤처확인종합관리시스템 벤처확인유형별 입수된 정보를 이용한 스톡옵
션 부여신고 간소화 서비스 추진ㆍ분석, 회원연계(중소벤처24) 분석
◦ 스톡옵션 데이터 및 문서 정제/적재 작업 수행
□ (시스템 구성) 벤처확인종합관리시스템 대민/백오피스 이원화 운영 中,
복수의결권, 스톡옵션 제도안내, 신청 등 서브메뉴 구성
◦ 스톡옵션, 복수의결권주식 확인 및 행정업무 수행을 위한 별도 백오피
스를 구성, 외부* 접속을 위한 접근제어 솔루션 탑재 여부 분석
* 공동인증서 로그인을 통해 접속 中, 개선방안 제시 및

=== index chunk 4 (800자) ===
 로그인 기록 보관
□ (시스템 기획) 스톡옵션, 복수의결권주식 정의 및 제도 이슈사항 등 분
석, 스톡옵선 부여신고, 복수의결권 행사에 관한 간편 신청, 자료연계(타
기관), 사용자 알림, 운영 모니터링, 통계 등 기획
◦ 벤처확인종합관리시스템 內 탑재를 위한 시스템 분석* 자료(영향도 분석)
제출
* 데이터 연계, 기정원 인프라 구성(TA분석), 상용SW 활용 및 Risk(라이선스 등) 분석
- 7 -
4 추진일정
□ 추진일정(안)
★ 복수의결권 1차 오픈일(‘24.07.10) 준수, 스톡옵션 GrandOpen(미정)
M-1 M M+1 M+2 M+3 M+4
주요내용
1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4
RFP 공고
기술/가격 협상 및 계약
착수보고
요구분석/설계
사
업
시스템 구축
추
진
사용자 교육
시스템 오픈 1차 오픈
운영 안정화
검사 및 검수, 테스트
□ 요구분석 및 설계 완료 후 중간보고 1회 진행, 시스템 고도화 및 테스
트(단위, 통합), 사용자 교육 최소 2회 이상, 완료보고 1회
◦ 중간보고 및 완료보고(중소벤처기업부, 벤처기업확인기관)
- 사용자 매뉴얼 작성, 업무용 매뉴얼을 통한 교육 2회
◦ 주 단위 시스템 진행 보고(벤처기업확인기관)
◦ 시스템 안정화를 위한 1개월 이상 안정화 운영인력 상주
- 8 -
Ⅲ. 사업 추진내용
1 복수의결권 / 스톡옵션 개념도
□ 메뉴 구성(안)
대민 내부 BackOffice
스톡옵션 복수의결권
부여신고 리스트 발행보고 리스트
부여신고 완료 발행보고 완료
부여신고 보류 발행보고 보류
부여신고 취소 발행보고

=== index chunk 5 (800자) ===
취소
스톡옵션 복수의결권
부여신고 출력 및 발송 발행보고 출력 및 발송
제도안내 제도안내
이상관제 이상관제
신청방법 신청방법
취소신고 리스트 변경신고 리스트
부여신고 발행보고
취소신고 완료 변경신고 완료
부여신고 결과 발행보고 결과
철회신고 취소 변경신고 보류
취소/철회 신고 발행고시(공시)
철회신고 완료 변경신고 취소
취소·철회 결과 변경보고
철회신고증 출력 및 발송 변경신고증 출력 및 발송
중기부 배정 현황 변경보고 결과
스톡옵션 통계(교차상세) 허위신고 접수
변경고시(공시)
제출서류 자료실 허위신고 조사
허위·거짓발행 신고
복수의결권 통계(교차상세)
제출서류 자료실
스톡옵션 통계 복수의결권 통계 관리기능 관리기능
스톡옵션 복수의결권 대민 제도안내(CMS) 대민 제도안내(CMS)
벤처확인 + 스톡옵션 벤처확인 + 복수의결권 담당자 알림 설정 담당자 알림 설정
연계 모니터링 연계 모니터링
제출서류 원본 제출서류 원본
제도 요건 설정 제도 요건 설정
열람 및 접속 로그 열람 및 접속 로그
※ 성과조건부주식교부 신고기능은 스톡옵션 기능 메뉴규성과 유사함
◦ 복수의결권주식 및 스톡옵션 내부 BackOffice는 별도로 구성되며, 대
민 및 내부 메뉴 구성에 대한 자세한 기획 및 제안
- 복수의결권 및 스톡옵션 업무시스템 메뉴 구성* 및 디자인 시안 제출
* 업무시스템 효율성을 고려한 최적의 메뉴 구성(안) 제안, 메뉴구성(안)의 명칭은 변경 보
완될 수 있음
□ (대민사이트) 벤처확인종합관리시스템 內 복수의결권주식, 스톡옵션 메
뉴로 구성
- 9 -
◦ (복수의결권) 복수의결권주식 발행(변경) 보고①, 복수의결권

=== index chunk 6 (800자) ===
주식 발행보고
결과(my페이지) 확인, 복수의결권주식 발행 통계③
- 복수의결권주식 발행보고 양식 출력
◦ (스톡옵션) 제도소개①, 스톡옵션 부여, 취소, 철회 신고② 및 신고방법 안
내③, 스톡옵션 부여신고 결과④, 스톡옵션 통계⑤ 등
- 스톡옵션 부여 신고자, 스톡옵션 부여 대상자 정보 확인 페이지 구축(스
톡옵션 신고 양식 출력)
- 스톡옵션 부여신고 지방청(13개) 자동 배정, 스톡옵션 부여신고(취소
ㆍ철회 포함)
□ (백오피스) 복수의결권주식 발행보고 및 스톡옵션 신고 업무처리를 위한
각 별도의 업무시스템 구축
◦ 중소벤처기업부 및 13개 지방중소벤처기업청 접속, 성과조건부주식교
부계약 업무처리 시스템도 동일하게 구축
◦ 벤처확인 이력정보* 연동 및 요건** 충족 여부 등의 이상 관제 모니터
링 기능 구현
* 벤처확인 재발급, 벤처확인 취소
** 공시대상기업집단 계열회사 편입, 기업상장 여부 등
- 스톡옵션 부여신고 자동배정 프로세스 구현, 스톡옵션 부여자 알림
기능, 업무 담당자별 차등 권한 등
- 10 -
2 업무 및 시스템 현황
□ (복수의결권주식) 「벤처기업육성에 관한 특별조치법」 시행에 따른 복수
의결권주식 발행 보고 기능 오픈 中
◦ 복수의결권주식 발행 보고(보완) 기능 고도화
◦ 비상장 벤처기업 요건 확인 후 복수의결권주식 발행, 사후관리(상장, 대
기업 집단편입 등) 모니터링 구현
□ (스톡옵션) 중소벤처24 內 벤처기업 스톡옵션 부여신고 기능으로 탑재되
어 운영되고 있는 스톡옵션DB 및 각종 자료 이관 및 검증작업
◦ 비상장 벤처기업 요건 확인 후 스톡옵션 부여신고, 새로운 기획을 통

=== index chunk 7 (800자) ===
한
스톡옵션 신청, 운영관리 구축
◦ 스톡옵션 신고 확인 관리자(BackOffice) * 페이지 별도 구성 中, 공동인증
서 로그인
* 중소벤처기업부, 13개 지방중소기업청 담당 공무원 로그인
- 스톡옵션 배정 및 처리현황 통계 기능 구축, 부여대상자 (부분)취소
기능개선 등
□ (인프라) 중소기업기술정보진흥원 클라우드(Paas-TA)환경에 설치 운영되
고 있으며, 벤처확인종합관리시스템 內 시스템 탑재에 따른 상용SW 적
용 가능
◦ 복수의결권주식, 스톡옵션 별도 관리자 시스템 구축을 위한 PaaS-TA
자원 할당(운영/개발) 제안
- 11 -
< 벤처확인종합관리시스템 인프라운영 현황 >
구 분 수 량 내 용
대민 WEB 1식 중소벤처24 이하 패밀리 사이트(WEB방식)
운영
Paas-TA 클러스터 1식
서버 내부망, Paas-TA환경, DB이중화
DB클러스터 2식
공통 SW&DEV클러스터 1식 운영 및 개발(UMS+MySQL, PDF변환기, PDF 뷰어, 통합검색)
대민 WEB 1식
개발
Paas-TA 클러스터 1식 WEB방식, 내부망, Paas-TA환경
서버
DB클러스터 1식
DATABASE 3식 PostgreSQL 4.8.5
개발 언어 2식 JAVA (JDK 1.8)
프레임워크 2식 전자정부 프레임워크 3.9
WAS서버 WAS서버(CentOS 8.0)
Web서버 Web서버(중소벤처24 웹서버 사용)
상용 SW 10종
차트툴 1식 SB Chart v2
PDF뷰어 1식 ePapyrus StreamDocs v1.0
PDF변환 1식 ePapyrus PDF Gateway v8.0
PKI공인인증 1식 MagicLi

=== index chunk 8 (800자) ===
ne v4.0
TouchEn nxKey v1.0-Explorer, TouchEn nxKey
키보드보안 1식
v1.0_Multi-Browser
업로드 1식 RAON K Upload 2018
검색엔진 1식 Konan Search 5
그리드 툴 1식 SBGrid v2.0
위변조방지 1식 e-Page SAFER V2.5 Basic Package
e-Page SAFER Web DRM Pack for Cross OS V2.5 Basic
화면캡쳐방지 1식
package
※ 중소벤처24 제공 서비스 : SSO 이지패스, 레포팅툴, DB암호화 솔루션
- 12 -
3 복수의결권 추진내용
□ 복수의결권주식 제도 요약
항 목 내 용
① 발행자격 및 보유자격
발행자격 비상장 주식회사인 벤처기업에 한정
보유자격 창업주로서 현재 회사를 경영하는 자(등기이사)
복수의결권주식 발행 대상이 되는 "창업주"의 의미: 아래의 요건을 모두 갖추어야 함
1) 벤처기업 설립 당시 정관에 기재된 발기인일 것
2) 주주총회에서 선임된 이사로서, 복수의결권주식 발행 당시 회사의 상무에 종사하는
이사일 것
3) 금고 이상의 실형을 선고받고 그 집행이 끝나거나 면제된 날부터 2년이 지나지 않은
자에 해당하지 않을 것
4) 벤처기업 설립 당시부터 가장 나중의 투자를 받기 전까지 계속하여 의결권 있는
발행주식총수의 30% 이상으로서 가장 많은 주식을 소유한 자일 것
5) 단, 1)~3)의 요건을 모두 갖춘 자가 2명 이상일 경우에는 그들이 소유한 주식을
합산하여 벤처기업 설립 당시부터 가장 나중의 투자를 받기 전까지 계속하여 의결권
있는 발행주식총수의 50% 이

=== index chunk 9 (800자) ===
상으로서 가장 많은 주식을 소유한 경우에는 각각을
창업주로 봄(이하 “공동창업주”)
② 발행요건
아래의 요건을 모두 갖추어야 함
1) 대통령령으로 정하는 특수관계인에 해당하지 아니하는 자로부터 대통령령으로 정하는
금액 이상의 투자를 받을 것(가장 나중에 받은 투자가 대통령령으로 정하는 금액
발행요건
이상이어야 함).
(투자요건)
2) 지분희석 우려*시
* 창업주 지분이 30% 이하로 떨어지거나, 공동창업주의 지분이
50%미만이 되는 경우
③ 발행한도
존속기간 발행 후 최대 10년 한도로 유효기간을 정관에 규정
의결권 수 1주당 최대 10개 한도로 기업이 정관에 규정
④ 절차・방법(정관변경→주총결의)
가중된 특별결의(발행주식총수의 ¾동의)로 정관 개정
[정관에 정할 사항]
1)일정한 경우 복수의결권주식을 발행할 수 있다는 뜻
2)복수의결권주식을 받을 자의 자격 요건
정관개정 3)복수의결권주식의 발행 절차
4)발행할 복수의결권주식의 총수
5)복수의결권주식의 1주당 의결권의 수 (1개 초과 10개 이하)
6)복수의결권주식의 존속기간 (최대 10년)
7)일정한 경우 복수의결권주식은 보통주식으로 전환된다는 뜻
가중된 특별결의로 복수의결권주식 신주 발행
[주총결의 사항]
1)복수의결권주식을 받을 자의 성명
2)복수의결권주식을 받을 자에 대하여 발행할 수량
발행결정
3)복수의결권주식 1주의 금액
4)복수의결권주식 납입에 관한 사항 (총주주의 동의가 있을 경우 보통주식으로
복수의결권주식에 대한 납입 가능-상법상 자기주식취득, 현물출자검사 조항
적용배제)
⑤ 보통주 전환요건
- 13 -
항 목 내 용
1)복수의결권주식의 존속

=== index chunk 10 (800자) ===
기간이 만료된 경우 (만료일 다음날)
2)창업주가 복수의결권주식을 상속하거나 양도한 경우 (상속일 또는
양도일)-주)일신전속적 권리의 성격
3)창업주가 이사의 직을 상실한 경우 (상실일)
4)벤처기업이 상장된 경우 (상장된 날부터 3년이 지난 날, 존속기간이 그 전에
보통주 전환
만료되는 경우에는 그 만료일의 다음날)
5)벤처기업이 공시대상기업집단 지정사실을 통지받거나 공시대상기업집단 계열회사
편입의 통지를 받은 경우 (통지일)
6)벤처기업이 공시대상기업집단 계열회사로 편입되어야 할 사유가 있음에도
대통령령에 해당하는 경우에 해당하여 제외 통지를 받은 경우 (통지일)
기 타 허위 또는 부정한 방법으로 발행시 그 발행일에 보통주식 발행으로 간주
⑥ 복수의결권 행사 제한
복수의결권 복수의결권 존속기간 변경을 위한 정관 변경, 이사의 보수, 책임의 감면, 감사 및 감사위원의
행사제한 선임 및 해임, 자본금 감소의 결의, 이익의 배당, 해산의 결의 시 1주 1의결권 행사
⑦ 특례
벤처기업이었던 벤처기업의 지위를 상실하는 경우에도 유효
기업의 특례 * 중소기업의 범위를 넘어서면서 벤처기업의 지위를 상실하는 경우에도 유효
공개매수 및 주식 복수의결권 발행 벤처기업은 자본시장법상 공개매수 및 대량보유 보고시 의결권
대량보유 보고 특례 기준으로 적용
⑧ 발행의 보고 및 고시
발행보고 복수의결권 발행내용 및 중요사항 변경시 중소벤처기업부에 보고
본점 등 공시 복수의결권 발행기업은 복수의결권주식 발행 내역 등을 본점과 지점에 비치 및 공시
관보고시 중소벤처기업부는 복수의결권 발행기업 명단, 주요사항 변경 등을 관보에 고시
⑨

=== index chunk 11 (800자) ===
허위발행죄 및 과태료
중소벤처기업부는 규정에 위반한 혐의가 있을 경우 직권으로 조사, 누구든지 위반한 사실이
위반행위 인지‧신고
있다고 인정할 때에 중소벤처기업부에 신고
보고(변경보고 포함)하지 아니하거나, 보고내용 허위작성시 500만원 이하 과태료,
과태료
비치 및 공시의무 위반시 300만원 이하 과태료
허위 또는 부정한 방법으로 복수의결권 발행한 자는
허위발행죄
10년 이하 징역 또는 5천만원 이하 벌금
- 14 -
□ (비상장 벤처기업) 복수의결권주식 발행보고 前 비상장 벤처기업 여부
확인, 요건 충족 기업만 가능
◦ (비상장) 복수의결권주식 발행보고 기업 법인등록번호 조회
- 대기업기업집단 계열회사 편입 여부(데이터포털 연계)
◦ (벤처확인) 복수의결권주식 발행보고 기업 사업자등록번호, 법인등록번
호, 벤처확인발급번호 조회
- (벤처확인 프로세스) 벤처확인 재확인, 또는 취소 (청문절차), 재발급
등 복수의결권주식 발행 신고 가능 여부 체크
- 주주총회 결의 시 벤처확인이 유효하다면 신청 가능
□ (복수의결권주식 기능개선) 복수의결권주식 발행보고 출력 기능개선, 기
업 My페이지 활동 이력
< My페이지 기업 활동이력 예시 >
벤처확인 복수의결권 스톡옵션
접수번호 : 20240215-M-00001 접수번호 : 20160410-S-00135
처리일 : 2024.02.15. 처리일 : 2016.04.10.
벤처확인발급번호 : 20220201 이상(코스닥 상장, 2024.05.10.) 이상(코스닥 상장, 2024.05.10.)
2022.02.01.~2025.01.31. 접수번호 : 20240215-M-

=== index chunk 12 (800자) ===
00001
확인정보 처리일 : 2024.02.15. -
정상
접수번호 : 20160410-S-00135
벤처확인발급번호 : 20160201
- 처리일 : 2016.04.10.
2016.02.01.~2018.01.31.
정상
① 벤처확인 이력 기준 복수의결권주식 발행보고, 스톡옵션 신고 이력이 있는 경우 노출
- 벤처확인 유효시작일~만료일 기간 내 정관개정을 통한 복수의결권주식 발행보고, 스톡옵션 신고 가
능
- 이상 : 대기업집단계열편입, 상장, 폐업/휴업 등이 있는 경우 표시
② 벤처확인이력 기준 복수의결권주식 발행보고는 ‘23.11.17부터 가능, 스톡옵션은 98년부터 신고 가능
- 사용자 활동이력은 업무시스템에 동일하게 노출되도록 구현
③ 벤처확인발급번호, 복수의결권주식 접수번호, 스톡옵션 접수번호 기준 출력 기능개발
- 15 -
◦ (정관변경) 특별결의를 통한 변경 정관 업로드 기능 구현
※ 엄격한 주주동의, 발행주식 총수의 4분의 3이상 동의로 가결
◦ 특수관계인으로부터 받은 투자를 제외한 투자금액이 누적 100억원 & 마
지막 50억원 이상
◦ 벤처확인 정보 연동을 통한 사용자 정보 입력 간소화
◦ 복수의결권주식 발행보고/보완/결과 통보/알림 기능 구현
◦ 제출서류 업로드 기능 구현(제출서류 이력 관리 기능 포함)
- (필수) 정관, 주주총회 의사록, 주주명부, 기타 업로드
- 업로드 파일명 규칙 적용(기업명_파일명_일자)
<복수의결권주식(발행, 변경) 필수 기재 항목>
구 분 항 목 설 명
접수번호 복수의결권주식 고유 접수번호
접수일자 복수의결권주식 발행 접수일자
업무담당자
처리일 복수의결권주식

=== index chunk 13 (800자) ===
발행 승인 처리일자
처리기간 복수의결권주식 발행 절차 소요기간
업체명 벤처확인서 정보 연동
대표자 벤처확인서 정보 연동
사업자등록번호 벤처확인서 정보 연동 및 조회
법인등록번호 벤처확인서 정보 연동 및 조회
벤처기업확인서 발급번호 벤처확인서 정보 연동 및 조회
전화번호 회사 대표 연락처
전자우편 보고자 전자우편
소재지 벤처확인서 정보 연동 또는 수기 입력
복수의결권주식을 받은자의 창업주, 공동창업주 선택을 통한 성명, 발행 수량 기
성명 및 발행 수량 재
복수의결권주식의 발행일자
복수의결권주식
복수의결권주식의 의결권 수
보고자
창업주 보유 보통주 납입 여부
전환일자 복수의결권주식이 보통주로 전환된 경우 기재
전환사유 복수의결권주식이 보통주로 전환된 경우 기재
투자일자 복수 입력 가능
투자유치금액(특수관계인 포함) 복수 입력 가능
투자유치금액(특수 관계인 제외) 복수 입력 가능
투자 전 창업주 지분율 복수 입력 가능
투자 후 창업주 지분율 복수 입력 가능
합계 투자유치금액 및 투자 후 창업주 지분율
복수의결권주식 발행, 변경 발행, 변경에 따른 접수번호 별도 관리
보고서 제출 년/월/일 보고서 신청일자 = 접수일자
- 16 -
보고인 성명 복수의결권주식 발행 신청인의 휴대폰 인증 정보
서명
첨부파일 제출된 첨부서류
※ 복수의결권주식 (발행, 주요사항 변경) 보고서 양식 제공, 보고서 양식 분석을 통환 시스템
화면 기획 필요
□ (대기업 집단 포함 시 보통주 전환) 공시대상기업집단에 포함된 기업이
독립성 인정 등 사유로 기업집단에서 제외되더라도(대기업 집단이 아니게
되어도) 보통주로 전환
◦ 보통주 전환관리 기능

=== index chunk 14 (800자) ===
 구현, 상속, 양도, 창업주의 이사 사임 등에 관
한 보통주 전환 신고기능 구축
<사후변경에 따른 복수의결권주식의 보통주 전환>
사후변경의 유형 전환 여부
상속 또는 양도
창업주의 이사 사임 즉시 전환
공시대상기업집단 포함
상장 상장 후 최대 3년까지 유효
벤처기업 지위 상실 이미 발행된 복수의결권주식 존속 기한까지 계속 유효
□ (복수의결권주식 발행보고) 복수의결권주식 받은 자의 성명, 발행일자,
발행 수량을 벤처확인종합관리시스템 공시
◦ 복수의결권주식 발행보고서 문서 출력 기능 구현
◦ 「벤처기업육성에 관한 특별조치법 시행규칙」 별지 제9호 참고
□ (복수의결권주식 변경보고) 복수의결권주식 받은 자의 성명, 발행일자,
발행 수량, 변경 일자, 변경 수량 변경 신고기능 구현
◦ 복수의결권주식 변경보고서 문서 출력 기능 구현
- 변경 신고 완료 후 복수의결권 발행 변경 전/후 비교 정보 출력
◦ 변경보고→변경 보완→변경 검토→변경보고 결과 통보 및 공시
◦ 복수의결권주식 변경사항 공시 기능 구현
- 17 -
□ (복수의결권 위반(허위 거짓)발행 신고기능) 복수의결권주식 발행 위반행
위 신고기능 구현
◦ (신고인) 성명, 주소 기재, 연락처, 이메일
- 개인정보 수집 및 이용 동의 절차 기능 구현, 신고자 통신사 인증
◦ (피신고인) 상호, 주소, 대표자 성명, 위반행위 내용, 위반행위 내용을
명확히 할 수 있는 사항(자료 업로드 등)
- (조회) 복수의결권 발행 번호, 법인등록번호 또는 사업자등록번호
◦ 신고인 실명→신고서 작성→신고접수 및 사실확인(조사)→신고접수 내
용 통보(신고인, 피신고인)
- 위반행

=== index chunk 15 (800자) ===
위 신고작성 방법 안내 페이지 구현
□ 복수의결권주식 통계, 제도소개, 신청방법 및 절차, 복수의결권 발행/변
경 공시 등의 안내 페이지 구현
- 18 -
4 스톡옵션 추진내용
□ (데이터 이관) 중소벤처24 內 벤처기업 스톡옵션(주식매수선택권) 신고를
위해 가입된 회원정보* 및 과거 각종 데이터/문서 이관
* 벤처확인종합관리시스템 內 탑재를 위한 회원 중복가입 등 데이터 검증(회원통합)
□ 스톡옵션 신고1) 프로세스 및 신고 관리영역2), 알림영역3), 통계영역4), 물
량배정5) 등으로 기능 구현
1) 회원가입 및 로그인, 부여 신고에 필요한 정보연계, 벤처확인이력 조회ㆍ적용, 각종 첨
부파일 등록 등
2) 스톡옵션 신고 관리자 시스템 구현, 벤처확인 이력정보 연계 등을 통한 주식매수선택
권 연계 상태 확인 기능, 신고(접수,보완,확인,통보) 관리 기능 등
3) 신고접수 및 보완요청, 최종수리 단계별 신고자 알림서비스
4) 벤처기업 스톡옵션 통계(부여 금액별, 산업분류별, 지역별, 자격별 등), 스톡옵션 자동배
정/보완/처리 통계 개발
5) 스톡옵션 신고 물량 배정 기능 구축(중소벤처기업부 지방청)
□ (주요 첨부파일) 스톡옵션 부여 신고에 따른 정관 사본1), 주주총회 의사
록2) 첨부, 주식매수선택권 일부를 이사회에 위임되는 경우 이사회 의사
록3) 추가 첨부, 기타 추가서류 업로드
- 업로드 파일명 규칙 적용(기업명_파일명_일자)
□ (근거법률) 스톡옵션 신고 및 행사 요건(벤처기업법 제15조, 제16조의3, 제16조
의4, 제16조의5, 제16조의6) 등 안내
* 벤처기업법 제16조의3 비상장 벤처

=== index chunk 16 (800자) ===
기업 확인
** 비과세특례 16조의2, 납부특례 16조의3, 과세특례 16조의4
◦ (벤처확인 여부) 스톡옵션 부여신고 정보를 이용한 벤처확인 이력 정보
조회(벤처확인 유효기간 內 신청 가능)
- 주주총회 결의 시 벤처확인이 유효하다면 신청 가능, 과거 벤처확인이
- 19 -
력이 있는 경우 해당 유효기간 내 주주종회 결의시 신청 가능
- 그 외, 벤처(재)확인, 벤처확인 재발급 프로세스, 벤처확인 취소 심의
단계 등 진행 체크
☞ (기능 구축) 대민사이트 스톡옵션 신고 前 증권시장(유가증권시장, 코스탁
시장, 코넥스시장)에 상장되지 않은 비상장 벤처기업 여부 확인
< 비상장 벤처기업 여부 조회(안) >
1안) 비상장/벤처기업 동시 조회
① 로그인 → ② 법인등록번호, 사업자등록번호 입력 → ③ 상장여부(법인등록번호) 및 벤처확인 여부 조회
→ ④ 스톡옵션 신고
2안) 벤처기업 조회 / 비상장 별도 확인
① 로그인 → ② 법인등록번호, 사업자등록번호 입력 → ③ 벤처확인 여부 조회 → ④ 스톡옵션 신고 → ⑤
각 지방청 비상장 별도 확인
□ (스톡옵션 통계) 스톡옵션 부여/변경신고 현황(연도별) 통계1), 부여대상
통계2), 행사가액 통계3) 등 표와 그래프 형태로 구축
1) 연도별 스톡옵션 기업수, 인원수, 주식수, 행사총액, 평균 행사가액
2) 대상자(임직원 및 그 외) 기준, 연도별 부여 건수, 대상자 직종, 대상자 행사 평균
3) 연도별 행사가격 분포
4) 그 외 벤처확인 데이터 매칭을 통한 통계(유형, 지역, 업종, 매출 등)
□ (스톡옵션 배정) 시스템 배정 조건에 따른 스톡옵션 부여 신고 (재)배

=== index chunk 17 (800자) ===
정
기능 구축
◦ (배정) 신고→배정→접수→보완ㆍ검토ㆍ확인→통보(알림)
- 배정 조건 外 부득이 재배정 이슈가 발행할 수 있음, 부여신고 접수
번호를 통한 재배정 이력 조회 기능 구축(지방청 배정 이력 전체 조회 가
능)
□ 업무(관리)시스템은 별도 외부 접속이 가능하도록 구축, PKI공동인증서
솔루션을 이용한 관리자 로그인 방식, ID로그인 방식 등 다양한 로그인
방식 기획
- 20 -
◦ 스톡옵션 부여신고 내역 조회1), 상세페이지2), 통계/분석3), 시스템 관리
4) 기능, 신고자 관리5) , 스톡옵션 부여신고 취소ㆍ철회 처리 기능 등
기획/설계 구축 진행
□ 스톡옵션 부여신고
◦ 비상장 벤처기업 조회 후 스톡옵션 부여 신고서 작성 기능 구현
◦ (출력) 「벤처기업육성에 관한 특별조치법 시행규칙」 별지 제3~4호 참고
※ (중요) 기재된 화면은 참고자료이며, 별도 화면 기획 및 제안 진행
1. 기업정보, 업무 담당자 입력 간소화 방안 기획
- 기업명, 대표자명 등 일반적인 입력정보
2. 사업자등록번호, 벤처확인발급번호 등을 통한 주식
매수선택권 부여 신고 가능 조회기능 탑재
3. 벤처확인정보 연계
-벤처확인발급번호, 벤처확인일, 유효시간
※ 벤처확인이력조회가 되지 않는 경우 문의
case1. 벤처확인만료
case2. 사업자등록번호와 벤처확인정보 불일치
case3. 벤처확인만료일 기준 벤처재확인 프로세스 진행 中
1. 부여주식종류 별도 코드로 관리
2. 액면가 단위(원), 숫자한글정보 표기
3. 부여인원 주식수, 행사가격 총합과 동일해야 함
- 21 -
1. 정관에 “스톡옵션(주식매수선택권)주식의 행사기

=== index chunk 18 (800자) ===
간”
이 규정되어 있는지 여부 中 행사기간은 주식매수
선택권 부여 결의사항 행사기간과 연동되어 체크되
어야 함
1. 주주총회특별결의, 이사회 결의에 따른 입력창, 페
이지부터 임시저장 기능 활성화
1. (+)연번 추가를 통한 부여인원 등록, 부여인원 대량
등록기능 개발
- 부여인원의 핸드폰번호 등록(개인정보보호에 관한
신고자 대리 등록에 따른 등록 동의)
- 핸드폰번호를 통해 부여된 인원의 부여주식 정보
안내
- 자격, 부여방법 코드값으로 관리,
- 부여인원 주식 총합 자동 계산
2. 항목별 첨부파일 업로드 복수
□ 스톡옵션 취소(부분)/철회 신고
◦ 스톡옵션 부여 신고 건에 대한 주식매수선택권 피부여자 (부분)취소, 철회
기능
- (부분)취소, 철회 신고 통보 결과 기능 구현
- 피부여자 취소 및 철회 신고 사항 알림 기능 구현
- 22 -
□ 스톡옵션 부여대상자
◦ 부여대상자는 시스템 로그인 후 My페이지를 통해 스톡옵션 부여 현황
및 행사 정보 확인
< My페이지 스톡옵션 부여대상자 예시 >
스톡옵션 부여주식 주식 행사
부여방법 :
기업명 : ㈜ OOOO 부여주식수 :
행사 주식수 : 주
접수번호 : 20160410-S-00135 행사가격 :
행사 일자 :
연락처 : 02-0000-0000 부여주식 종류 :
행사기간 :
부여방법 :
기업명 : ㈜ ㅁㅁㅁㅁ 부여주식수 :
행사 주식수 : 주
접수번호 : 20191010-S-00010 행사가격 :
행사 일자 :
연락처 : 032-0000-0000 부여주식 종류 :
행사기간 :
- 23 -
Ⅳ. 제안요청 내용
1 과업수행방법
□ 과업착수
◦ 본 시스템 기능 고

=== index chunk 19 (800자) ===
도화 용역사업은 과업 시작일로부터 10일 이내 착수하
여야 함
◦ 계약상대자는 계약체결일로부터 10일 이내 다음과 같은 서류를 벤처확
인기관에 문서로 제출해야 함
∨ 착수계
∨ 책임기술자 선임계
∨ 책임기술자 이력서 및 기술자격증 사본
제출서류 목록 ∨ 참여기술자 이력서 및 기술자격증 사본
∨ 보안각서 및 보안대책
∨ 과업수행계획서
∨ 기타 필요사항
□ 과업수행계획서 제출
◦ (과업수행계획서) 계약서, 과업내용서 등의 내용을 근거로 작성
◦ (계획승인) 계약상대자는 과업수행계획서를 벤처기업확인기관의 승인을 득
한 후 이에 따라 과업 수행
◦ (계획서의 변경) 계약상대자는 부득이한 사유로 과업수행계획서의 내용
을 변경하고자 하는 경우 벤처기업확인기관의 승인을 받아 계획서를
변경할 수 있음
- 24 -
2 제안요청 일반사항
□ 제안 업체는 시스템 기능 고도화 완료 후 기능 확장성 등을 고려하여
제안하여야 함
□ 제안 업체는 제안하는 모든 부분에 포괄적인 책임을 가지며, 제안 시점
에서 사업수행요건 미충족 업체는 선정 대상에서 제외함
□ 제안규격의 만족 여부는 벤처기업확인기관에서 제시하는 평가 기준 등
에 의해 심사함
□ 전산시스템 운용 및 유지관리에 대처할 수 있는 구체적 기술이전, 교육
계획 및 지원계획을 제시해야 함
□ 특별한 사유가 없는 한 본 시스템 기능 고도화사업은 사업 기간 中 개
발 완료 및 테스트 가능하여야 하며, 하자 보증기간 내 하자보수 및 유
지관리 계약이행에 대한 모든 책임을 져야 함
□ 안정적이고 확장 가능한 최적의 시스템 개발하며 개발업무의 각종 서식
및 코드, 시스템 간 통합 및 연계,

=== index chunk 20 (800자) ===
 전산 망간 연계 등 정보화 표준을
준용하여 개발해야 함
□ 시스템 개발과정에서 취득한 일체 모든 정보는 외부로 유출 또는 발설
해서는 안 되며, 만약 사업 과정에서 보안사고 발생 시 업체에서는 일
체 민형사상의 책임을 지고, 벤처기업확인기관이 입은 손해에 대하여
배상해야 함
- 25 -
3 제안요청 필수사항
□ ①보안성을 고려한 시스템 구성 및 운영방안, ②보안성 강화 및 관리의
용이성을 위한 추가지원 가능 사항(필요시)을 제시해야 함
□ 시스템 장애 발생 시, 즉각 복구할 수 있는 체제를 구축해야 함
□ 향후 시스템 확장성을 위해 시스템 기능 고도화 관련 표준을 최대한 준수
□ 계약 전에 본 요청서를 비롯한 기타 계약서류를 조사 검토하여 시행하여야
하며, 의문 사항은 중소벤처기업부, 벤처기업확인기관의 의견을 확인하고
계약 후에는 중소벤처기업부, 벤처기업확인기관의 해석과 관계 법규를
준수하여야 함
□ 제안서에 기재되지 않은 사항이라 할지라도 제품성능에 필요한 사항은
벤처기업확인기관과 협의를 통해 공급(납품)하여야 함
□ 최종 인수 결과 시스템 운영 불가로 ‘계약조건 미충족’으로 판단 시, 벤
처기업확인기관의 요구에 의해 구축한 모든 시스템을 철거·회수하여야
하며, 그 비용은 제안업체에서 일체 부담하고 이로 인한 벤처기업확인
기관의 손해를 배상해야 함
□ 본 과업의 시스템은 유기적으로 데이터 교환이 가능하여야 하며, 타 기관
의 시스템 연계가 가능해야 함
□ 시스템 기능 고도화 과정에서 취득한 정보에 대한 보안 관리 방법 등에
대한 제시 및 시스템 구축 후 하자보수를 위한 방안을 제시해야 함
- 26 -
4

=== index chunk 21 (800자) ===
제안 요구사항
□ 요구사항 정의표
요구
분류기준 세부 내용
사항수
- 목표시스템이 반드시 수행하여야 하거나 목표
기능 요구사항
시스템을 이용하여 사용자가 반드시 수행할 수 38
(SFR, System Function Requirement)
있어야 하는 기능(동작)에 대하여 기술
성능 요구사항 - 목표시스템의 처리속도 및 시간, 처리량, 동적‧
5
(PER, Performance Requirement) 정적용량, 가용성 등 성능에 대한 요구사항을 기술
시스템장비구성 요구사항 - 목표 사업 수행을 위해 필요한 하드웨어, 소프트
(ECR, Equipment Composition 웨어, 네트워크 등의 도입 장비 내역 등 시스템 5
Requirement) 장비 구성에 대한 요구사항을 기술
- 목표시스템과 외부를 연결하는 시스템 인터페
인터페이스 요구사항 이스와 사용자 인터페이스에 대한 요구사항을
(SIR, System Interface Requirement & 기술한 것으로 타 소프트웨어, 하드웨어 및 통신 9
UIR, User Interface Requirement) 인터페이스, 타 시스템들과의 정보교환에 이용
되는 프로토콜과의 연계도 포함하여 기술
- 목표시스템의 서비스에 필요한 초기자료 구축 및
데이터 요구사항
데이터 변환을 위한 대상, 방법, 보안이 필요한 데이터 10
(DAR, Data Requirement)
등 데이터를 구축하기 위해 필요한 요구사항을 기술
- 도입되는 장비의 성능 테스트(BMT) 또는 구축된
테스트 요구사항
시스템이 목표 대비 제대로 운영되는가를 테스트 5
(TER, Test Require

=== index chunk 22 (800자) ===
ment)
하고, 점검하기 위한 테스트 요구사항을 기술
- 정보 자산의 기밀성과 무결성을 확보하기 위해
보안 요구사항
목표시스템의 데이터 및 기능, 운영 접근을 통 9
(SER,Security Requirement)
제하기 위한 요구사항을 기술
- 목표 사업의 원활한 수행 및 운영을 위해 관리가
품질 요구사항
필요한 품질 항목, 품질 평가대상 및 목표에 대 6
(QUR,Quality Requirement)
한 요구사항을 기술
- 목표시스템 설계, 구축, 운영과 관련하여 사전에
제약사항
파악된 기술·표준·업무·법제도 등 제약조건 등을 7
(COR, Constraint Requirement)
파악하여 기술
프로젝트 관리 요구사항 - 프로젝트의 원활한 수행을 위한 관리 방법 및
10
(PMR, Project Management Requirement) 추진 단계별 수행방안에 대한 요구사항을 기술
프로젝트 지원 요구사항 - 프로젝트의 원활한 수행을 위해 필요한 지원
9
(PSR, Project Support Requirement) 사항 및 방안에 대한 요구사항을 기술
합 계 113
※ 사업 내용이 변경될 경우 과업변경절차에 따라 상호 협의하여 결정하며, 제안서 작성 시 제안요청서 요구사
항에 명시되지 않았으나 제안 업체 판단으로 추가되어야 할 요구사항에 대해서는 별도 표시하여 추가 작성
가능함
- 27 -
□ 요구사항 상세
가 기능 요구사항(System Function Requirement)
요구사항 고유번호 SFR-001
요구사항 분류 기능 요구사항
요구사항 명칭 사용자 인증 기능 구현
정의 시스템 기업/사용자 인증

=== index chunk 23 (800자) ===
기능 구현
❍ 복수의결권주식 신청자/창업주/대리인 확인절차 기능 기획 및 구현
요구사항 ❍ 스톡옵션 신청자/부여(대상자) 확인절차 기능 기획 및 구현
상세설명 세부내용 ❍ 주민등록번호 미수집에 따른 대체 인증 방안 제시
❍ 벤처확인종합관리시스템 회원통합을 위한 인증방안 제시 및 구현
❍ 복수의결권주식, 스톡옵션 업무 담당자 인증
산출 정보 요구사항정의서, 프로그램 명세서, 개발 산출물
요구사항 고유번호 SFR-002
요구사항 분류 기능 요구사항
요구사항 명칭 회원가입
정의 벤처확인종합관리시스템 회원통합
❍ 중소벤처24 스톡옵션 신청자 회원통합 방안/기획 및 기능 구현
❍ 중소벤처24 Easy Pass 연계
요구사항
❍ 벤처확인종합관리시스템 이관사용자와의 회원통합
상세설명 세부내용
❍ 중소벤처24 스톡옵션 신청자 회원통합 이력 조회 기능 구현
❍ 벤처확인종합관리시스템을 통한 복수의결권주식, 스톡옵션 업무 담당자 회원가
입(現기업회원(법인) > 복수의결권, 스톡옵션 업무 담당자 회원가입)
산출 정보 요구사항정의서, 프로그램 명세서, 개발 산출물
요구사항 고유번호 SFR-003
요구사항 분류 기능 요구사항
요구사항 명칭 중소기업확인서
정의 복수의결권주식 발행보고 및 스톡옵션 부여신고 前 중소기업여부 확인
❍ 중소기업확인서 발급정보 연동
요구사항

In [9]:
# 문서별 pred_map 저장 (옵션)
pred_dir = out_dir / f"exp{spec.exp_id:02d}_pred_maps"
pred_dir.mkdir(parents=True, exist_ok=True)

saved = 0
for _, row in doc_df.iterrows():
    doc_id = str(row["doc_id"])
    pred_map = row.get("pred_map", None)
    if isinstance(pred_map, dict):
        # 파일명 안전화
        safe = re.sub(r"[\\/:*?\"<>|]", "_", doc_id)
        path = pred_dir / f"{safe}.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(pred_map, f, ensure_ascii=False, indent=2)
        saved += 1

print("Saved pred_maps:", saved, "->", pred_dir)

Saved pred_maps: 20 -> /Users/won/dev/00_codeit/0_mission/200_DL_RAG/outputs/exp03_pred_maps

### 디버깅(선택)

In [10]:
DEBUG = True  # 필요할 때만 True

if DEBUG:
    print("last_debug:", getattr(rag.generator, "last_debug", None))

    raw = getattr(rag.generator, "last_raw_text", "") or ""
    print("raw_text_len:", len(raw.strip()))
    print("raw_text_preview:\n", raw[:600])

    d = getattr(rag.generator, "last_resp_dump", None)
    print("dump is None?", d is None)
    if isinstance(d, dict):
        # responses API는 output_text가 별도 필드로 있을 수 있음(덤프엔 없을 때도 있음)
        print("top keys:", list(d.keys())[:30])
        print("status:", d.get("status"))
        usage = d.get("usage") or {}
        print("usage.output_tokens:", usage.get("output_tokens"))
        out = d.get("output")
        if isinstance(out, list):
            print("output item types:", [x.get("type") for x in out if isinstance(x, dict)])

last_debug: {'model': 'gpt-5-mini', 'n_questions': 1, 'context_len': 1525, 'max_context_chars': 4000, 'prompt_len': 2447, 'response_status': 'completed', 'output_tokens': 202, 'output_text_repr': '\'{"eligibility":"조달청 입찰참가자격등록증 소지업체;「국가를 당사자로 하는 계약에 관한 법률 시행령」제12조 및 시행규칙 제14조에 의한 경쟁입찰 참가자격; 부정당업자의 입찰참가자격 제한 대상 제외(입찰 등록 마감일 기준, 동법 시행규칙 제76조); 「소프트웨어 진흥법」에 의한 소프트웨어사업자(컴퓨터 관련 서비스사업, 업종코드: 1468) 등록 \'', 'exception': None, 'parse_error': None}
raw_text_len: 297
raw_text_preview:
 {"eligibility":"조달청 입찰참가자격등록증 소지업체;「국가를 당사자로 하는 계약에 관한 법률 시행령」제12조 및 시행규칙 제14조에 의한 경쟁입찰 참가자격; 부정당업자의 입찰참가자격 제한 대상 제외(입찰 등록 마감일 기준, 동법 시행규칙 제76조); 「소프트웨어 진흥법」에 의한 소프트웨어사업자(컴퓨터 관련 서비스사업, 업종코드: 1468) 등록 및 최근년도 결산신고 된 SW사업자신고확인서 제출; 하도급 불가; 공동수급 시 관련법 준수; 핵심참여인력은 제안서대로 반드시 투입 및 필요시 즉시 교체·대체인력 투입 요구"}
dump is None? False
top keys: ['id', 'created_at', 'error', 'incomplete_details', 'instructions', 'metadata', 'model', 'object', 'output', 'parallel_tool_calls', 'temperature', 'tool_choice', 'tools', 'top_p', 'background', 'completed_at', 'conversation', 'max_output_tokens', 'max_tool_calls', 'previous_response_id', 'prompt', 'prompt_cache_key', 'prompt_cache_retention', 'reasoning', 'safety_identifier', 'service_tier', 'status', 'text', 'top_logprobs', 'truncation']
status: completed
usage.output_tokens: 202
output item types: ['reasoning', 'message']

In [11]:
# (옵션) GEN_FAIL/NOT_FOUND 비율 빠르게 보기: 마지막 doc 1개 기준
try:
    last_row = doc_df.iloc[-1].to_dict()
    pm = last_row.get("pred_map")
    print("pred_map sentinel counts:", count_sentinels(pm))
except Exception as e:
    print("pred_map sentinel counts: skipped:", repr(e))

pred_map sentinel counts: {'n_keys': 11, 'n_not_found': 1, 'n_gen_fail': 0}

In [14]:
# RAGAS 평가 (선택)
# 전제: 위 실험 셀(spec, RUN_DOCS, gold_evidence_df, embed_model, client)이 실행된 상태
import sys
from pathlib import Path
try:
    from preprocess.ragas_eval import run_experiment_with_ragas
except ModuleNotFoundError:
    notebooks_dir = BASE_DIR / "notebooks"
    if str(notebooks_dir) not in sys.path:
        sys.path.insert(0, str(notebooks_dir))
    from preprocess.ragas_eval import run_experiment_with_ragas

ragas_result = run_experiment_with_ragas(
    spec=spec,
    run_docs=RUN_DOCS,
    gold_fields_jsonl_path=GOLD_FIELDS_JSONL,
    embed_model=embed_model,
    client=client,
    evaluator_model="gpt-5-mini",
    ragas_metrics=["faithfulness", "context_precision", "answer_correctness"],
    compute_baseline_doc_metrics=False,  # 이미 위에서 계산했다면 False 권장
    gold_evidence_df=gold_evidence_df,
    sim_threshold=80,
    judge_max_context_chars_per_sample=5000,
    judge_max_output_tokens=400,
    judge_reasoning_effort="minimal",
)

display(ragas_result.ragas_exp_df.round(4))

a_out = BASE_DIR / "outputs"
a_out.mkdir(parents=True, exist_ok=True)
ragas_exp_out = a_out / f"exp{spec.exp_id:02d}_ragas_explevel.csv"
ragas_doc_out = a_out / f"exp{spec.exp_id:02d}_ragas_doclevel.csv"
ragas_sample_out = a_out / f"exp{spec.exp_id:02d}_ragas_sample.csv"

ragas_result.ragas_exp_df.to_csv(ragas_exp_out, index=False, encoding="utf-8-sig")
ragas_result.ragas_doc_df.to_csv(ragas_doc_out, index=False, encoding="utf-8-sig")
ragas_result.ragas_sample_df.to_csv(ragas_sample_out, index=False, encoding="utf-8-sig")
print("Saved:", ragas_exp_out)
print("Saved:", ragas_doc_out)
print("Saved:", ragas_sample_out)

RAG + RAGAS | exp 3: 100%|██████████| 20/20 [11:15<00:00, 33.76s/it]
GPT-5 judge scoring: 100%|██████████| 220/220 [05:14<00:00,  1.43s/it]

   exp_id  faithfulness  context_precision  answer_correctness
0       3         0.774               0.76              0.7985

Saved: /Users/won/dev/00_codeit/0_mission/200_DL_RAG/outputs/exp03_ragas_explevel.csv
Saved: /Users/won/dev/00_codeit/0_mission/200_DL_RAG/outputs/exp03_ragas_doclevel.csv
Saved: /Users/won/dev/00_codeit/0_mission/200_DL_RAG/outputs/exp03_ragas_sample.csv